### ISSUE TITLE
Fix typos in the docs

### ISSUE THREAD

**Issue by prometherion** [clastix/capsule#10]
Pretty straightforward, there are several typos in the documentation that sounds terrible in the English language.

Help is wanted, so please don't hesitate to refer to this issue while contributing to fixing small typos on Capsule! :tada:

**Comment by YashThakare** [comment]
I wanted to work on this project . In which file is typos mistakes exactly ?

**Comment by prometherion** [comment]
Hi @YashThakare and thanks for the help! :rocket: 

I'm pretty confident that the [use-cases document](https://github.com/clastix/capsule/blame/bd7218ba44881c52263d987c8160430931da4e11/use_cases.md) contains several of that, as well the [README](https://github.com/clastix/capsule/blame/bd7218ba44881c52263d987c8160430931da4e11/README.md).

Please, open a PR once you found some of them and reference it using the [autolinked referencing](https://docs.github.com/en/github/writing-on-github/autolinked-references-and-urls).

**Comment by prometherion** [comment]
Just discovered a typo [here](https://github.com/clastix/capsule/blame/master/.github/ISSUE_TEMPLATE/bug_report.md#L24): _behaviour_ should be _behavior_.

**Comment by bsctl** [comment]
I think https://github.com/clastix/capsule/pull/48 resolves it.
