### ISSUE TITLE
How can Owner track the list of namespaces created  

### ISSUE THREAD

**Issue by AdheipSingh** [clastix/capsule#103]
# Bug description

- I deployed capsule with 0.0.1 tag, and created alice user using the hack script.
- Deployed tenant using the sample config provided
- As per sample tenant an owner ( alice ) can create upto 3 namespaces.
- What my query is how can alice track how many namespaces she has created or how can alice know what all namespaces she is responsible for ?

# How to reproduce
- Basically with the alice kubeconfig, i cant do ```kubectl get namespaces```  ( which  is right since ns is cluster scoped )
- But at the same time i cant track the ns i created, deleted etc.

# Additional context

- Capsule version: (`0.0.1`)
- Kubernetes version: (`1.17`)

**Comment by prometherion** [comment]
Thanks for the bug report, really appreciated!

We're going to provide an additional utility that will allow Tenant Owner to list Namespaces created, without any additional RBAC at cluster scope and without any additional kubectl plugin or additional CRD 

This project will be released next week, going to provide you the link to it!

**Comment by prometherion** [comment]
As promised, [`capsule-ns-filter`](https://github.com/clastix/capsule-ns-filter) is a simple Kuberentes API decorator that empowers Tenant owner capabilities to list their namespaces without the need of additional RBAC! 🚀 

Closing this issue, any further inquires should be opened on that repository.
