### ISSUE TITLE
Storage Class policy is not applied to Persistent Volume Claims generated from StatefulSets

### ISSUE THREAD

**Issue by bsctl** [clastix/capsule#105]
# Bug description
Storage Class policy is not applied to Persistent Volume Claims generated from StatefulSets. Only PVCs directly created by the user are subject to the policy. PVCs created from a StetefulSet template are not subject to the Storage Class policy defined at tenant level.

# How to reproduce
As cluster admin, create a tenant with a StorageClass policy.
Login as tenant owner and:

- create a PVC with not permitted Storage Class: the request is denied
- create a STS with a PVC template using a not permitted Storage Class: the request is accepted and the PVC is created.

# Expected behavior
STS having a PVC template with not permitted Storage Class should be denied

# Logs

# Additional context

capsule v0.0.1
kubernetes 1.19.2

**Comment by prometherion** [comment]
Nice catch and this can be applied to any other Service Account, so applies also to Ingress Class.

We have to make the webhook logic more generalist and not relying just on the user ownership, got PR ready for this.
