### ISSUE TITLE
Tenant names with dashes are denied by admission webhook

### ISSUE THREAD

**Issue by d-m** [clastix/capsule#113]
# Bug description

Tenant names with dashes fail admission we hook with "Tenant name has forbidden characters." Do dashes cause an issue or is this solely due to the regex used?

# How to reproduce

1. Attempt to creat a Tenant resource with name "test-tenant"

# Expected behavior

A tenant with the name "test-tenant" is created. 

# Logs

```
Error: admission webhook "tenant.capsule.clastix.io" denied the request: Tenant name has forbidden characters
```

**Comment by prometherion** [comment]
It seems we have a regex, there:

https://github.com/clastix/capsule/blob/ee6e3aa0df79ada668d68f3a174eb09ae2617bc5/pkg/webhook/tenant/validating.go#L67-L70

I recall a discussion with @MaxFedotov that implemented that, also according to `git blame`, but honestly I don't recall what's the downside of having dashes on Tenant name. Pretty sure, the Tenant name is used across referenced resources to allow selection, but we just need to adhere to DNS RFC-1123.

Please, Max, would you mind providing a reminder behind this designing decision?

**Comment by MaxFedotov** [comment]
Hi, 
this was related to https://github.com/clastix/capsule/issues/76#issuecomment-688826105
Without this restrictions, we are unable to distinguish namespace name from tenant name

**Comment by d-m** [comment]
Ah I see. This may cause some issues for my use case. I'm trying to map Tenant resources to some exists groups I have, but some of these groups have dashes. I'd like to keep them if possible so that the namespace prefixes make sense to the users, since they're familiar with the group names they're in. 

Unfortunately, I can't drop the dashes for the Tenant name since I sometimes have other groups that would then conflict. For example, unique groups "abc" and "ab-c".

**Comment by prometherion** [comment]
I think we can try to make an effort and solve this problem from the upside-down, rather.

I just opened a PR and would be nice having feedback from @MaxFedotov since I guess we can easily implement it when test suite is green! :)

**Comment by prometherion** [comment]
Good news @d-m: with the latest contributions Capsule now accepts also Tenant names with dashes as DNS RFC-1123 🎉 

Please, give it a try building Capsule from `master` and feel free to open back this issue in the case is not working as expected.
