### ISSUE TITLE
Question: duplicated nested loops in the code

### ISSUE THREAD

**Issue by bsctl** [clastix/capsule#117]
We're looking at #106 and noted a couple of nested loops we're not understanding:
https://github.com/clastix/capsule/blob/ee6e3aa0df79ada668d68f3a174eb09ae2617bc5/pkg/webhook/tenant_prefix/patching.go#L87-L102

What's the purpose of them? It looks the desired condition of #106 is already addresses by `return admission.Denied("The namespace doesn't match the tenant prefix, expected " + e) `

but it looks that code is never reached.

**Comment by prometherion** [comment]
I would say it's a bug, let me test the hotfix for this, although is not critical: it's just a matter to don't repeat an already performed task.
