### ISSUE TITLE
clastix/capsule:latest tag not found

### ISSUE THREAD

**Issue by ams0** [clastix/capsule#124]
# Bug description

The `make deploy` quickstart creates a capsule-controller-manager pod with image pointing to `quay.io/clastix/capsule:latest` which doesn't exist.

# How to reproduce

`make deploy` in the root of this git repo checkout (master)

# Expected behavior

Pod container image either pointing to `quay.io/clastix/capsule:v0.0.1` or tag the image on quay with `latest`

# Logs

# Additional context

- Capsule version: (`capsule --version`): 0.0.1
- Kubernetes version: (`kubectl version`) 1.19.0 on Azure Kubernetes Service

**Comment by prometherion** [comment]
You're totally right and it's my bias: `latest` is an anti-pattern and is just used during the development phase but we have to consider also bare installation from source code, so thanks for reporting this!

**Comment by ams0** [comment]
Even better would be to mention and present the helm chart installation method in the readme in this repo; I found out about the helm chart after I pulled a lot of go dependencies:). Might consider moving the chart here too under /charts

P.S. hello Dario!

—-
Live long and prosper
________________________________

**Comment by bsctl** [comment]
@ams0 Thanks Alessandro for reporting this. Just updated the README by mentioning the Helm installation.

**Comment by prometherion** [comment]
> Might consider moving the chart here too under /charts

Yes, it's something we're sorting out but we were too tightened on time with some features and bugs but thanks for adding this point, we'll plan to deliver it ASAP!
