### ISSUE TITLE
The docker image is built with wrong tag version

### ISSUE THREAD

**Issue by bsctl** [clastix/capsule#134]
# Bug description
When building from master branch with `make docker-build` the produced artefact is labeled as:

```
Successfully built 4482ce7dd7aa
Successfully tagged quay.io/clastix/capsule:0.0.1 
```

Currently the image should be tagged as `latest`

# How to reproduce

```
$ git pull https://github.com/clastix/capsule
$ cd capsule
$ make docker-build
$ docker images |grep capsule
```

# Expected behavior
Tag image tagged with latest tag.

# Logs

If applicable, please provide logs of `capsule`.

In a standard stand-alone installation of Capsule,
you'd get this by running `kubectl -n capsule-system logs deploy/capsule-controller-manager`.

# Additional context

- Capsule version: (`capsule --version`)
- Kubernetes version: (`kubectl version`)

**Comment by bsctl** [comment]
@prometherion not really convinced by #127. Building from master branch should tag the image as `latest` instead of the current release. We can have the master branch ahead of the current release, eg. `v0.0.2`.  In such case, the image built from master branch is different from the image stored on the public repo `quay.io/clastix/capsule`.

**Comment by prometherion** [comment]
`latest` is an anti-pattern and should be avoided at all since it's mutable.

Building from `master` should produce a build with the upcoming patch release with a suffix of the commit SHA, but that's something out of our control, right now: if an end-user would like to use `latest` free to do that, but I'd like to strongly discourage this.

**Comment by bsctl** [comment]
> `latest` is an anti-pattern and should be avoided at all since it's mutable

This is not the case, imho. The image built from master branch is actually the `latest` artefact available for the users. It is **actually different** from the official release stored on the public repo. Having both the images (one from repo and another one from make build) labeled with the same tag will confuse the users.

> Building from master should produce a build with the upcoming patch release with a suffix of the commit SHA

Do you mean something like `v0.0.2-xyz`?
