### ISSUE TITLE
Changing required fields for Tenant resource

### ISSUE THREAD

**Issue by bsctl** [clastix/capsule#145]
I would review the required fields in Tenant resource. Currently (v0.0.3), in `capsule.clastix.io/v1alpha1`, we have:

|field                      |required   |webhook    |controller |
|---------------------------|-----------|-----------|-----------|
|owner                      |*          |*          |           |
|nodeSelector               |           |           |*          |
|namespaceQuota             |*          |*          |           |
|namespacesMetadata         |           |           |*          |
|servicesMetadata           |           |           |*          |
|ingressClasses             |*          |*          |           |
|storageClasses             |*          |*          |           |
|containerRegistries        |           |*          |           |
|additionalRoleBindings     |           |           |*          |
|resourceQuotas             |           |           |*          |
|limitRanges                |*          |           |*          |
|networkPolicies            |           |*          |           |

To make Capsule more flexible and address more use cases, we can leave only the `owner` field as mandatory. All the other fields will be optional.

@prometherion @MaxFedotov @gdurifw what do you think? What prevents this from technical pov?

**Comment by prometherion** [comment]
I couldn't agree more and, honestly, you got me in before: as you probably noticed, for some Tenant specification fields we're using the `,omitempty` tags: this should allow us to avoid putting empty values during test cases as well, and, last but not least, increasing the Capsule flexibility.

Definitely, LGTM but eager to hear others' opinions.

**Comment by bsctl** [comment]
@prometherion I would raise the priority of this issue. By rewriting the documentation with an "user stories" approach, I feel the Capsule user's experience will be improved by limiting the required field only to the ownership. This because, the user approaching Capsule, can easily become comfortable with it by just trying one feature at time.

**Comment by prometherion** [comment]
There's still a blocker for 0.1.0 releae and it's #49.

That issue is quite tricky and haven't figured yet a way to solve it, so we could postpone it to `0.2.0` or any next patch version since it's just an enhancement.

**Comment by prometherion** [comment]
I just realized we could have another blocker, `namespaceQuota`.

How should Capsule behave when this limit is not declared? Right now, we got also the additional printer column on `kubectl get tnt -o wide`, and last but not least, how to deal when a Cluster Admin assign a Namespace quota lower than the already registered Namespaces (I'd say we have to block that).

Any thoughts on this?

**Comment by bsctl** [comment]
> I just realized we could have another blocker, `namespaceQuota`

I got a feedback from customer, they are not to use this constraint leaving the tenants to create namespaces as much they want. Actual constraints will be `resourceQuota`. In such case they have to put namespaceQuota=999 for example  but this looks a bit ugly. My suggestion is to make this optional and show namespaceQuota=0 in the printed column where, by convention, zero means infinite. Sorry to my mathematicians friends :)

**Comment by bsctl** [comment]
> how to deal when a Cluster Admin assign a Namespace quota lower than the already registered Namespaces (I'd say we have to block that).

I just got a new test case :)

**Comment by MaxFedotov** [comment]
I totally agree with having only owner as required field in spec. As capsule is growing with new features, it becomes really hard for a new user to understand them all. So It will be much better to allow to start only with owner field in spec, and then if needed to update spec with additional features.

**Comment by prometherion** [comment]
It seems we acquired a full RAFT consensus on this design! 🤣
