### ISSUE TITLE
Use more comprehensive variables in the code-base

### ISSUE THREAD

**Issue by prometherion** [clastix/capsule#164]
We should keep an eye on the variables names we're using in the code-base: as developers and core contributors, it's easy for us understanding their purposes, not the same for newcomers.

_Originally posted by @paolocarta in https://github.com/clastix/capsule/pull/162#discussion_r541976465_

**Comment by paolocarta** [comment]
I could take it as soon as I will be done with #157 .

**Comment by prometherion** [comment]
Hey @paolocarta are you still working on this?

**Comment by paolocarta** [comment]
@paolocarta No I am not at the moment. Feel free to assign it in case!

**Comment by ludusrusso** [comment]
Hi @prometherion , I'd like to give a try!

**Comment by prometherion** [comment]
> @prometherion No I am not at the moment. Feel free to assign it in case!

Thanks @paolocarta, appreciated it!

**Comment by ludusrusso** [comment]
@prometherion just started working on it, what does `wl` stands for here? I think "webhooks" but I don't get the "l" :D

https://github.com/clastix/capsule/blob/12237ae106d6e9bbcb49e1091318534a901f29cd/main.go#L169

**Comment by prometherion** [comment]
Closed via #245.
