### ISSUE TITLE
Update the coding style guide

### ISSUE THREAD

**Issue by prometherion** [clastix/capsule#165]
We're not documenting the no-new-line at the beginning of a new function in the coding style documented for Capsule.

_Originally posted by @prometherion in https://github.com/clastix/capsule/pull/162#discussion_r542398228_

**Comment by bsctl** [comment]
@prometherion is this just a matter of update the `contribution.md` file?

**Comment by prometherion** [comment]
Yes, and documenting also the use of [semantic git commit messages](https://www.conventionalcommits.org/en/v1.0.0/).

Along with this, we should also put in place the relative GH action, I can take care of this so you can work on the docs.

**Comment by prometherion** [comment]
- [x] [Implement CI action to check the commit message](https://github.com/clastix/capsule/pull/393)
- [ ] Documenting the Conventional git Commit Messages
- [ ] Documenting required new-line at the end of the file as a coding style
