### ISSUE TITLE
Document how to increase logs level

### ISSUE THREAD

**Issue by bsctl** [clastix/capsule#17]
It would be nice to have a configurable logs level for the capsule controller, e.g. info, warning, debug, trace, .. This will help during troubleshooting.

**Comment by prometherion** [comment]
Actually we're logging whatever we can at `info` level and OperatorSDK already provides, via `zap`, a configurable logging verbosity: using a single level has been just a lazy choice since, at this phase, every information is vital but a medium priority is reasonable, here.

**Comment by prometherion** [comment]
@bsctl since we're relying on OperatorSDK that uses `zap`, you can specify an additional _argument_ to the Capsule deployment using the following notation: `--zap-level={0...10}`.

I don't think we should reinvent the wheel, let's us the opinionated way without the need to pass additional arguments, so closing the issue.

**Comment by bsctl** [comment]
> I don't think we should reinvent the wheel, let's us the opinionated way without the need to pass additional arguments, so closing the issue.

Agree 💯 

However from the average kubernetes user point of view, we have to document it. Reopening and assigning to documentation.

**Comment by prometherion** [comment]
@bsctl do you think that reporting how to increase logs on [contributing.md](https://github.com/clastix/capsule/blob/aab0d9b6579b556fe52f6df340ecc1bdec02c480/contributing.md) is enough or should we add a new section?

If yes, wondering _where_ :sweat_smile:

**Comment by bsctl** [comment]
> If yes, wondering _where_ 😅

IMO a short note in the main README should be enough, just after the how to run section. Generally speaking, we need a review of the whole documentation.

**Comment by prometherion** [comment]
> we need a review of the whole documentation

Absolutely true.

We could start considering to implement documentation using a static site (e.g.: Jekyll hosted with GitHub Pages) or the broadly adopted _Mkdocs_.

**Comment by bsctl** [comment]
> @bsctl since we're relying on OperatorSDK that uses `zap`, you can specify an additional _argument_ to the Capsule deployment using the following notation: `--zap-level={0...10}`.

is this missing in more recent builds?

**Comment by bsctl** [comment]
#48 update documents
