### ISSUE TITLE
Tenant backup and restore of a Tenant

### ISSUE THREAD

**Issue by prometherion** [clastix/capsule#2]
# Describe the feature

It looks that [Velero](https://github.com/vmware-tanzu/velero) is the most suitable solution to handle Kubernetes cluster backups, although meaning adding a new dependency besides the already required admission plugins.

However, we should ignore specific Tenant that doesn't need a backup strategy due to end-user business logic (e.g. tiering).

Would be great if we could easily label the Namespace resources to let Velero skips all the underlying resources.

# What would the new user story look like?

1.  [feature request](https://github.com/vmware-tanzu/velero/issues/2413) implemented in Velero
2. adding a `.spec.backup` boolean flag into Tenant definition
3. Capsule ensures that the selected label is available on all the handled Namespace resources
4. Capsule ensures the PV used by the PVC is labeled with the said one since Persistent Volume are cluster-scoped resources.

# Expected behavior

Toggling the backup flag into Tenant definition, Velero should ignore or not the backup of the Tenant resources.

**Comment by bsctl** [comment]
@prometherion we can implement this new feature without depending on Velero even if this looks like the most suitable solution in the open source space.

From Capsule operator point of view, we just need to put additional labels to the tenant leaving the cluster admin to give specific semantics to these labels, according to the implemented business logic.

**Comment by prometherion** [comment]
I'm not getting the point, here: please, can you try to elaborate a bit more? I'm really interested.

**Comment by bsctl** [comment]
Just free thinking here ... The idea is to leave an additional section in the Tenant manifest where the Cluster admin can specify additional labels to apply to the namespaces in the tenant. Initially, there are no specific semantics assigned to these labels, they just will be assigned to the namespaces in the tenant. This can be useful to implement further features, giving a sort of _programming interface_ to the Capsule operator.

```yaml
apiVersion: capsule.clastix.io/v1alpha1
kind: Tenant
metadata:
  name: oil
spec:
  additionalNamespaceLabels:
  - capsule.clastix.io/backup: "true"
  - capsule.clastix.io/billable: "true"
  - capsule.clastix.io/do_stuff: "once"
  ingressClasses:
  - default
...
```
 
Depending on the case, the Cluster admin can implement additional business logics using these labels. For example, he can implement a backup service for namespaces having the label `capsule.clastix.io/backup: "true"` and this is not tied to velero or any other specific backup solution. Does it make sense?

**Comment by prometherion** [comment]
Feature proposal sounds legit, even if the `.spec.backups` field would be totally useless with this scenario.

I'm not saying that it would be wrong: Capsule should just be responsible to manage the Tenant abstraction dealing with the underlying Namespace resources, and probably this feature request should be closed although we're still lacking of feedbacks (and I'm eager of them).

Using Velero would be great but could be a huge dependency lockin, using labels (and I would say, also annotations) would be better.

Let's keep this open and asking for a discussion.

**Comment by bsctl** [comment]
@prometherion sure we can keep the above feature request separated from this specific #2. Will open a new enhancement to address the above request and leave #2 only for backup.

**Comment by bsctl** [comment]
> Using Velero would be great but could be a huge dependency lockin, using labels (and I would say, also annotations) would be better.

@prometherion should we close this? Since #80 we can add additional labels/annotations to namespaces belonging to a tenant. Assuming the backup solution will be able to operate per namespace, e.g. https://github.com/vmware-tanzu/velero/issues/18, this use case can be accomplished in that way.

**Comment by prometherion** [comment]
Yes, I would say we're good enough: in case, just need to open this back.
