### ISSUE TITLE
Let the tenant owner to know the assigned Storage Classes

### ISSUE THREAD

**Issue by bsctl** [clastix/capsule#21]
# Describe the feature
Let the tenant owner (and other any tenant user) to know the list of Storage Classes available in the tenant. Currently, because of RBAC, the tenant owner cannot get the available storage classes. The suggested approach is to put a readonly  annotation in each namespace of the tenant. The annotation reports the list of Storage Classes assigned to the tenant. For example: `capsule.clastix.io/storage-classes: "ceph,longhorn,standard"`. 

# What would the new user story look like?

1. What are the prerequisites for this?
2. Tenant owner creates a new namespace
3. Tenant owner check the annotations in the namespace and get list of assigned Storage Classes
4. Tenant owner creates a pvc in the namespace using the one of the available Storage Classes
5. Capsule controller is happy of this and lets the pvc to be created.

# Expected behavior
As tenant owner (or as any other tenant user) I want to know which Storage Classes are available in my tenant.

**Comment by prometherion** [comment]
Same here, I can work on this: #4 got higher priority.
