### ISSUE TITLE
Capsule builds are always .dirty

### ISSUE THREAD

**Issue by prometherion** [clastix/capsule#213]
We're having this output log that is useful when debugging Capsule to understand if the binary has been built with noncommitted changes that could lead to issues.

https://github.com/clastix/capsule/blob/2ea36db5d6a38cf15d777c2e34e4f9494ed0664b/main.go#L68

This variable is set at build-time, as following.

https://github.com/clastix/capsule/blob/2ea36db5d6a38cf15d777c2e34e4f9494ed0664b/Dockerfile#L21-L32

However, all the images are marked with `dirty` field, even the ones built using clean `git status` or through the CI system.

```json
{"level":"info","ts":"2021-03-04T07:31:44.732Z","logger":"setup","msg":"Capsule Version v0.0.5-rc1 737b6ce.dev.dirty"}
```

**Comment by davideimola** [comment]
Hi @prometherion! I would like to work on this issue!
Thanks!
