### ISSUE TITLE
Prevent ingress hostname collision

### ISSUE THREAD

**Issue by bsctl** [clastix/capsule#215]
# Describe the feature
Currently it is possible to create multiple ingresses with same ingress hostname across different tenants and within the same tenant as well.

# What would the new user story look like?
A new CLI flag `--allow-ingress-hostname-collision` is added, defaulted to `true` to reflect current behaviour and do not break things. When set to `false`, Capsule will check if the Ingress hostname is already assigned to another ingress across different tenants and within the same tenant as well.

The check happens only in the Namespace resources managed by Capsule.

# Expected behavior
A configurable way to avoid ingress hostname collision

**Comment by prometherion** [comment]
Actually, we're allowing Ingress hostname collision: default value must be `true`.

**Comment by bsctl** [comment]
> Actually, we're allowing Ingress hostname collision: default value must be `true`.

this should be reflected into #214

**Comment by bsctl** [comment]
Update the bug description according to https://github.com/clastix/capsule/issues/215#issuecomment-791559641
