### ISSUE TITLE
Let the tenant owner to know the assigned Ingress Classes

### ISSUE THREAD

**Issue by bsctl** [clastix/capsule#22]
# Describe the feature
Let the tenant owner (and other any tenant user) to know the list of Ingress Classes available in the tenant. Currently, because of RBAC, the tenant owner cannot get the available Ingress classes. The suggested approach is to put a readonly annotation in each namespace of the tenant. The annotation reports the list of Ingress Classes assigned to the tenant. For example: `capsule.clastix.io/ingress-classes: "haproxy,nginx,standard"`.

# What would the new user story look like?
What are the prerequisites for this?
Tenant owner creates a new namespace
Tenant owner check the annotations in the namespace and get list of assigned Ingress Classes
Tenant owner creates an ingress in the namespace using the one of the available Ingress Classes
Capsule controller is happy of this and lets the ingress to be created.

# Expected behavior
As tenant owner (or as any other tenant user) I want to know which Ingress Classes are available in my tenant.

**Comment by prometherion** [comment]
This feature request sounds really good: working on it but first, I have to complete the #4: I should be able to commit some code before the end of the week, at last.
