### ISSUE TITLE
Support for Arm-based Docker images

### ISSUE THREAD

**Issue by prometherion** [clastix/capsule#244]
# Describe the feature

Actually, all the Docker images are built using the `amd64` architecture.

https://github.com/clastix/capsule/blob/12237ae106d6e9bbcb49e1091318534a901f29cd/Dockerfile#L27

Capsule should be runnable also on Arm and Arm64-based infrastructures since there are plenty of projects running Kubernetes at the edge.

# What would the new user story look like?

1. Definitely, we have to switch from quay.io based Docker image creation to GitHub Actions, requiring to provide a new GitHub Secret to allow push of built Docker images
2. Using [`docker buildx`](https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/) to allow the creation of multi-arch images
3. Evaluate if we need a hub.docker.com account

# Expected behavior

Running `clastix/capsule:v0.0.5` (YMMV) container image on an Arm-based Kubernetes cluster, Capsule should be up and running.

**Comment by ptx96** [comment]
Done some tests on arm and arm64 platforms;

here we have some critical points:
- the bitnami/kubectl image used inside "jobs" is not ready for arm use;
  instead I'd take a look at [kubesphere](https://hub.docker.com/r/kubesphere/kubectl) -> TESTED OK, I'll modify default helm chart values for this ;
- RBAC Proxy image is not ready for arm use -> REMOVED with [#246 PL](https://github.com/clastix/capsule/issues/246) ;
- docker build is striclty dependant from GOARCH var (and other flags) and it's impossible to produce only one multiarch manifest directly using _docker buildx_ -> actually trying [goreleaser](https://github.com/goreleaser/goreleaser.git)

**Comment by prometherion** [comment]
> * the bitnami/kubectl image used inside "jobs" is not ready for arm use;
>   instead I'd take a look at [kubesphere/kubectl](https://hub.docker.com/r/kubesphere/kubectl) -> TESTED OK, I'll modify default helm chart values for this ;

LGTM

> * docker build is strictly dependant from GOARCH var (and other flags) and it's impossible to produce only one multiarch manifest directly using _docker buildx_ -> actually trying [goreleaser](https://github.com/goreleaser/goreleaser.git)

Let's move out the build process from Docker to goreleaser

**Comment by prometherion** [comment]
According to latest PR, few updates.

- we're going to provide a Clastix `kubectl` container image since we noticed some missing supported architectures
- no need for `goreleaser`, in the end, we can easily use the base `golang:1.16` container image with a target architecture with build provided by the GH Action `docker/build-push-action@v2`
