### ISSUE TITLE
Remove the RBAC proxy

### ISSUE THREAD

**Issue by prometherion** [clastix/capsule#246]
Capsule is exposing [Prometheus metrics](https://github.com/clastix/capsule/blob/12237ae106d6e9bbcb49e1091318534a901f29cd/main.go#L127-L134) provided by the `controller-runtime`

However, we're [forcing the metrics endpoint to bind to the Pod loopback](https://github.com/clastix/capsule/blob/12237ae106d6e9bbcb49e1091318534a901f29cd/charts/capsule/templates/deployment.yaml#L49) and the `kube-rbac-proxy` sidecar container kicks in.

This is an inheritance from the scaffolding provided by Operator SDK, and the reason is to protect the metrics endpoint from the scraping of unauthorized users.

However, since Capsule is considered to be put in its Namesace and protected by Network Policy, we don't need that extra-overhead, otherwise, an operator would configure Prometheus to scrape using a Bearer Token provided by the [metrics reader role](https://github.com/clastix/capsule/blob/12237ae106d6e9bbcb49e1091318534a901f29cd/charts/capsule/templates/rbac.yaml#L21-L31).

My proposal is to remove the said sidecar container and bind the metrics endpoint to 0.0.0.0.

WDYT @bsctl @MaxFedotov?

**Comment by bsctl** [comment]
@prometherion it can be considered safe from my side.

**Comment by MaxFedotov** [comment]
Lgtm, let's remove it
