### ISSUE TITLE
Align Helm charts to latest changes

### ISSUE THREAD

**Issue by prometherion** [clastix/capsule#256]
- [x] [migrate to admission.k8s.io/v1](https://github.com/clastix/capsule/blob/49e1f088ad931e52d28cffb1bdb3c5b60c12bc05/config/webhook/manifests.yaml)
- [x] [update the CRD](https://github.com/clastix/capsule/blob/49e1f088ad931e52d28cffb1bdb3c5b60c12bc05/config/crd/bases/capsule.clastix.io_tenants.yaml)
- [x] [multiple `capsule-user-groups` changed the ClusterRoleBinding that must be cleaned-up upon Chart removal](https://github.com/clastix/capsule/pull/260/commits/d3f42efd130bac2a5c5fb32a7b5c1f9f97c7a4af)

**Comment by prometherion** [comment]
I think we're in a good shape, here: are we still missing something?

**Comment by bsctl** [comment]
New features are going to be consolidated now so we can start to work on that. PR will follow

**Comment by prometherion** [comment]
We can close this, CRD on the Helm Chart folder is already aligned.

**Comment by bsctl** [comment]
> We can close this, CRD on the Helm Chart folder is already aligned.
@prometherion not yet pls, just finding small errors in the chart
