### ISSUE TITLE
Use multiple groups as capsule-user-group

### ISSUE THREAD

**Issue by bsctl** [clastix/capsule#258]
# Describe the feature
Currently, only user requests belonging to the group specified in `--capsule-user-group` are managed by Capsule. In some cases, there are users in different groups that need to use Capsule and it is not always possible to create a new dedicated common group and move all the existing users into it (think a large legacy AD/LDAP user base managed by a corporate security team).

It would be nice to specify a list of groups as `--capsule-user-groups=capsule.clastix.io,engineering,sudoers,sysadmins`.

# What would the new user story look like?

How would the new interaction with Capsule look like? E.g.

1. What are the prerequisites for this?
2. Tenant owner creates a new _Namespace_
3. This is going to be attached to the _Tenant_
4. All the magic happens in the background

Feel free to add a diagram if that helps explain things.

# Expected behavior
User requests belonging to users in the specified groups `--capsule-user-groups=` are managed by the Capsule Controller.

**Comment by MaxFedotov** [comment]
seems like this would be breaking change in CRDs and require a new version

**Comment by prometherion** [comment]
I don't think that the @bsctl aim is to assign a Tenant to a group of users, but rather just increase the audience of allowed groups allowed and enforced to the Capsule multi-tenancy.

Pretty sure, we have to try to avoid the breaking of CLI flags: I'm not a big fan of the comma-separated list of values, we need to check if we can go for `--capsule-user-group=capsule.clastix.io --capsule-user-groups=engineering --capsule-user-groups=sudoers` in order to don't break the CLI flags signature.

**Comment by MaxFedotov** [comment]
what do you think if we switch to https://github.com/spf13/pflag instead of native golang flag? it is drop-in replacement and it supports arrays(https://pkg.go.dev/github.com/spf13/pflag#StringSliceVar), so we can replace 
```
var capsuleGroup string
flag.StringVar(&capsuleGroup, "capsule-user-group", capsulev1alpha1.GroupVersion.Group, "Name of the group for capsule users")
```
with
```
import flag "github.com/spf13/pflag"
var capsuleGroup []string
flag.StringSliceVar(&capsuleGroup, "capsule-user-group", []string{capsulev1alpha1.GroupVersion.Group}, "Names of the groups for capsule users")
```

**Comment by MaxFedotov** [comment]
@prometherion  if you are ok with this, I will do this task

**Comment by prometherion** [comment]
Sure, let's go for `github.com/spf13/pflag`, also because it's already imported by the actual dependencies.

```
$ go mod why github.com/spf13/pflag
# github.com/spf13/pflag
github.com/clastix/capsule/pkg/webhook/utils
k8s.io/client-go/tools/clientcmd
github.com/spf13/pflag
``` 

@MaxFedotov you got a new issue assigned! :D
