### ISSUE TITLE
Adding Owner and Age as additional printer columns

### ISSUE THREAD

**Issue by prometherion** [clastix/capsule#26]
# Describe the feature

An additional printer column reporting the Tenant owner name would be great.

# What would the new user story look like?

Implementation is really easy, just need to add the kubebuilder`printcolumn` annotation into the Tenant type.

Feel free to add a diagram if that helps explain things.

# Expected behavior

```
# kubectl get tenants.capsule.clastix.io
NAME   NAMESPACE QUOTA   NAMESPACE COUNT   OWNER
oil    3                 3                 alice
```

**Comment by bsctl** [comment]
it would be useful to have the AGE field too

```
# kubectl get tenants.capsule.clastix.io
NAME   NAMESPACE QUOTA   NAMESPACE COUNT   OWNER    AGE
oil    3                 3                 alice    5d10h
```

**Comment by prometherion** [comment]
> it would be useful to have the AGE field too

It seems that adding additional printer columns is not reporting anymore the `AGE` default one: removing [these](https://github.com/clastix/capsule/blob/5d20d515a760e4698a707e3297d11416bc32c1b0/config/crd/bases/capsule.clastix.io_tenants.yaml#L11-L19) is behaving as expected.

```
# kubectl get tenants.capsule.clastix.io
NAME   AGE                                                                                                                                                                                                                                    
oil    117m 
```

Opened an issue on [`kubectl`](https://github.com/kubernetes/kubectl/issues/903) just to clarify this behavior, but I guess we have to add it to play safe.

**Comment by bsctl** [comment]
@prometherion already noted this, it looks like you have to enforce in CRD

```yaml
      additionalPrinterColumns:
      - name: owner
        type: string
        description: owner
        jsonPath: .spec.owner
      - name: region
        type: string
        description: region
        jsonPath: .spec.region
      - name: namespaces
        type: integer
        description: namespaces
        jsonPath: .status.size
      - name: Age
        type: date
        jsonPath: .metadata.creationTimestamp
```
