### ISSUE TITLE
Get rid of Docker hub images

### ISSUE THREAD

**Issue by prometherion** [clastix/capsule#272]
It's absolutely annoying getting the [container image builds blocked by the Docker Hub rate limiting](https://quay.io/repository/clastix/capsule/build/a7239dbe-dcff-4f90-a5ae-f4db3b758894).

Let's find a mirror of the `golang:1.16` builder image, as well as using a minified one.

**Comment by ptx96** [comment]
is there any limit on ECR public gallery?

public.ecr.aws/bitnami/golang:1.16

**Comment by prometherion** [comment]
ECR just rate limited me! 😅 

We could go for quay.io/notano/golang:1.16, there should not be problema since we're building from Quay!

WDYT?

**Comment by ptx96** [comment]
> ECR just rate limited me! 
> 
> We could go for quay.io/notano/golang:1.16, there should not be problema since we're building from Quay!
> 
> WDYT?

Sure, let's go with it!
