### ISSUE TITLE
hostNetwork support in helm chart

### ISSUE THREAD

**Issue by ruzickap** [clastix/capsule#308]
# Describe the feature

Would it be possible to add support for `hostNetwork` in helm chart?
This is necessary for managed clusters like Amazon EKS with custom CNI (such as Calico).

Details can be found here (for example): 
* https://github.com/jetstack/cert-manager/blob/15b6f32071b45687b44eb097145815fc3af1b010/deploy/charts/cert-manager/values.yaml#L304-L313
* https://github.com/jetstack/cert-manager/blob/15b6f32071b45687b44eb097145815fc3af1b010/deploy/charts/cert-manager/templates/webhook-deployment.yaml#L53-L55

Thank you

**Comment by prometherion** [comment]
I think that's ok, feel free to take this issue if you want to contribute by opening a PR!
