### ISSUE TITLE
How to get rid of Capsule

### ISSUE THREAD

**Issue by bsctl** [clastix/capsule#31]
We need to document how to uninstall the Capsule Operator from the current setup and how to clean everything it installs: pods, web-hooks, roles, crds, ...

**Comment by prometherion** [comment]
Should be easy, let's work with an additional make recipe: just need to use `kubectl delete -f -`

https://github.com/clastix/capsule/blob/ee0a238b7f80dcb492d8247d0664eef0ad6ed473/Makefile#L49-L52
