### ISSUE TITLE
v1beta1 additionalPrinterColumns for tenant owner info

### ISSUE THREAD

**Issue by MaxFedotov** [clastix/capsule#331]
In `v1alpha1` version of capsule, `tenant` can only have a single owner, so we added
```
// +kubebuilder:printcolumn:name="Owner name",type="string",JSONPath=".spec.owner.name",description="The assigned Tenant owner"
// +kubebuilder:printcolumn:name="Owner kind",type="string",JSONPath=".spec.owner.kind",description="The assigned Tenant owner kind"
```
to `additionalPrinterColumns ` in crd spec.

But in `v1beta1` it is possible to specify multiple owners for a tenant, and as `additionalPrinterColumns` doesn't support arrays (https://github.com/kubernetes/kubectl/issues/517) we need to find a solution how to show user information about tenant owners (or may be we don't need to show it at all)

@bsctl @prometherion need your ideas :)

**Comment by prometherion** [comment]
Since we're going for multiple owners, we could drop the support for the Owner columns, also because it's something out of our scope and a limitation of upstream Kubernetes project.

Let's wait @bsctl's feedback.

**Comment by bsctl** [comment]
Removing the field from CRD breaks some UIs we built on top of Capsule, including the customer one.

What about to keep the field in CRD and populate it with only the first element of the array? Sounds ugly … but doesn’t break the customer’s UI.

**Comment by bsctl** [comment]
@prometherion @MaxFedotov any idea how to solve this?

**Comment by prometherion** [comment]
> Removing the field from CRD breaks some UIs we built on top of Capsule, including the customer one.

We're not removing any field from the CRD, but rather we're talking about the additional printer column used by `kubectl`.

If any dashboard has been implemented on top of Capsule, there are no breaking changes until it uses the `v1alpha` endpoint rather than `v1beta1`, although the upgrade should be planned since the new version is going to support tenant owners.

> What about to keep the field in CRD and populate it with only the first element of the array?

For `v1alpha` it will be kept, but since `v1beta` implements multiple owners, we have to remove it.

**Comment by bsctl** [comment]
@prometherion Thanks got it.

**Comment by bsctl** [comment]
Noted already removed in master

```
$ kubectl get tnt
NAME   STATE    NAMESPACE QUOTA   NAMESPACE COUNT   NODE SELECTOR    AGE
gas    active   9                 0                 {"pool":"cmp"}   34m
gold   active   9                 0                 {"pool":"cmp"}   33m
oil    active   9                 0                 {"pool":"cmp"}   54m
```

going to close the issue?

**Comment by MaxFedotov** [comment]
@bsctl if you are ok with removing it - issue can be closed :)

**Comment by bsctl** [comment]
It looks like no way, according to comments above :)
