### ISSUE TITLE
Improve Velero Backup Restoration script

### ISSUE THREAD

**Issue by bsctl** [clastix/capsule#336]
# Describe the feature
Some small improvements of the Velero Backup Restoration script `hack/velero-restore.sh`

- support for multiple tenant crd api version: `v1beta1` and `v1aplha1`
- make `kubeconfig` file optional
- restore only the specified tenant not all (if the tenant is not specified on the command, then restore all tenants)

**Comment by prometherion** [comment]
> support for multiple tenant crd api version: v1beta1 and v1aplha1

JFI we just need to use `v1beta` since the UID is essentially the same, conversion is performed on Kubernetes side and, since we're delivering new versions, forcing new users to use the latest version.

tl;dr; let's update the script with `v1beta1` reference.

**Comment by bsctl** [comment]
@prometherion the script should work for v0.0.5 too as we have customers doing backup and restore with `v1alpha1` 

```
{
  "op": "add",
  "path": "/metadata/ownerReferences",
  "value": [
    {
      "apiVersion": "${apiVersion}",
      "blockOwnerDeletion": true,
      "controller": true,
      "kind": "Tenant",
      "name": "${tnt}",
      "uid": "${uid}"
    }
  ]
}
```

Currently, the api version `v1apha1` is hardcoded.
