### ISSUE TITLE
Outdated use-cases API version in documentation

### ISSUE THREAD

**Issue by prometherion** [clastix/capsule#345]
All the documentation on use-cases is referencing to the `v1alpha1` API version, we should update to `v1beta1` along with new features implemented.

**Comment by bsctl** [comment]
@prometherion good point. Also the [reference](https://github.com/clastix/capsule/blob/master/docs/operator/references.md) section should be updated.

**Comment by bsctl** [comment]
Going to assign myself since a refactoring of the whole documentation seems required
