### ISSUE TITLE
Refactoring the Tenant controller

### ISSUE THREAD

**Issue by MaxFedotov** [clastix/capsule#363]
tenant_controller.go codebase became too large to read, so I propose to split it into separate files for each of the resources it manages, like
```
controllers\tenant\
reconciler.go
utils.go
networkpolicy.go
limitrange.go
resourcequota.go
rolebinding.go
namespace.go
```

**Comment by prometherion** [comment]
@MaxFedotov JFI that wouldn't be a _chore_ but rather a _refactor_
