### ISSUE TITLE
Limiting amount of Resources a Tenant can create in its Namespace

### ISSUE THREAD

**Issue by prometherion** [clastix/capsule#365]
# Describe the feature

If a Cluster Admin wants to block the overall usage of Pods or any other Kubernetes default resource in the Tenant, the ResourceQuota feature is the perfect fit for this kind of limiting/enforcement.

But this doesn't cover the case of Namespaced Custom Resource Definitions that could be delegated using the `additionalRoleBindings` Tenant specification.

# What would the new user story look like?

1. As a Cluster Administrator I want to provide Tenant Owners the ability to create their instances of Namespaced Custom Resource, this is possible using the `additionalRoleBindings` specification
2. I want to enforce the maximum amount of resources a Tenant Owner can consume in their Namespaces (or Tenant)
3. A webhook should block the creation of new CRD instances if going over-quota

# Expected behavior

N.R.

**Comment by prometherion** [comment]
@bsctl would be great having feedback from you if we want to land this feature for the v0.1.0 release or not.

**Comment by bsctl** [comment]
@prometherion great proposal like it +1
