### ISSUE TITLE
Refactor NamespaceQuota and NamespaceMetadata in tenant spec

### ISSUE THREAD

**Issue by MaxFedotov** [clastix/capsule#369]
With the latest tenant spec updates, we implemented grouping of different kind-related options under some parent entities (for example, all options related to `Services` are grouped under `ServiceOptions` in `TenantSpec`). 

We had two namespace-related parameters in `TenantSpec` - `NamespaceQuota` and `NamespacesMetadata`

My proposal is to group them in a following way:
```
type TenantSpec struct {
	...
	// Specifies options for the Namespace resources, such as maximum number of namespaces allowed for that Tenant or additional metadata. Optional
	NamespaceOptions NamespaceOptions `json:"namespaceOptions,omitempty"`
	...
}
```

```
type NamespaceOptions struct {
        //+kubebuilder:validation:Minimum=1
	// Specifies the maximum number of namespaces allowed for that Tenant. Once the namespace quota assigned to the Tenant has been reached, the Tenant owner cannot create further namespaces. Optional.
	Quota *int32 `json:"quota,omitempty"`
	// Specifies additional labels and annotations the Capsule operator places on any Namespace resource in the Tenant. Optional.
	AdditionalMetadata *AdditionalMetadataSpec `json:"additionalMetadata,omitempty"`
}
```

**Comment by prometherion** [comment]
It's a +1 for me, let's wait @bsctl feedback.

Just a quick question: maybe is better to use `NamespaceOptions` as a pointer to allow `nil` values, otherwise we would end up with tenant specifications like the following.

```yaml
apiVersion: capsule.clastix.io/v1beta1
kind: Tenant
spec:
  owners:
  - kind: User
    name: alice
  namespaceOptions: {}
```

Not sure about this, we would need a little investigation for this.

**Comment by MaxFedotov** [comment]
I thought about it, but isn't quota a required param?

**Comment by prometherion** [comment]
Not anymore, starting from #145.

However, dealing with pointers in the specification is an hassle, we can check if we can combine the `Enum` provided by Kubebuilder with the `IntOrString` type provided by `k8s.io/apimachinery/pkg/util/intstr` package, so we could use an integer for the quota or the enum `Unlimited` for no quota at all.

**Comment by MaxFedotov** [comment]
@prometherion i don't understand which benifits will we have if using `intstr` :( As for me it makes everything more complicated. I if don't want to enforce quota for namespaces - I won't specify it in tenant spec. If I want it - I will specify the precise value.

**Comment by prometherion** [comment]
It was to avoid nil pointers, but at the same time with controller-gen we're having some issues with enums or pattern markers, so let's skip this and use a nil value as you suggested.
