### ISSUE TITLE
Update helm chart: unknown flag: --allow-ingress-hostname-collision

### ISSUE THREAD

**Issue by Cryptophobia** [clastix/capsule#370]
# Bug description

Need to update the helm chart to allow the `--allow-ingress-hostname-collision` on the manager container. Currently if we try to deploy `v0.1.0-rc5` with helm chart version `0.0.19` we get an error as below:

```bash
kubectl logs capsule-controller-manager-8d9db44fb-hc5tq -n capsule-system manager
unknown flag: --allow-ingress-hostname-collision
unknown flag: --allow-ingress-hostname-collision
```

# How to reproduce

Install with helm chart like this:
```bash
helm upgrade --install --set manager.image.tag=v0.1.0-rc5 -n capsule-system --wait capsule 
```

# Additional context

- Capsule version: v0.1.0-rc5
- Helm Chart version: 0.0.19
- Kubernetes version: Does not matter

**Comment by Cryptophobia** [comment]
Looks like a regression. Chart 0.0.18 works but chart 0.0.19 is broken with release candidate `v0.1.0-rc5`…

**Comment by prometherion** [comment]
Hey, thanks for the bug report! Actually, the latest RC are not yet compatible with the published Charts, I'd suggest you to use the bare Chart on the `master` branch or wait still few weeks since we're in the middle of the v0.1.0 release and a new Chart will be published, too.

**Comment by Cryptophobia** [comment]
Thanks for quick reply @prometherion. Can wait for new release. Feel free to close this. Cheers!
