### ISSUE TITLE
support `customLabels` in capsule helm chart

### ISSUE THREAD

**Issue by MaxFedotov** [clastix/capsule#386]
Sometimes users had some custom logic, which relies on labels that should be present on all application parts (deployment, service, rbac, etc). 

In many charts this is done via `customLabels` param in `values` (see https://github.com/kyverno/kyverno/blob/main/charts/kyverno/templates/_helpers.tpl#L40 as an example). 

@prometherion, @bsctl  What do you think about adding this param to `capsule` helm chart?

**Comment by prometherion** [comment]
LGTM!

**Comment by prometherion** [comment]
I'd say we could manage also additional Annotations, it shuold be easy to achieve.
