### ISSUE TITLE
Align the installer to use the default configuration name for CapsuleConfiguration

### ISSUE THREAD

**Issue by bsctl** [clastix/capsule#394]
The installer sets the configuration name for `CapsuleConfiguration` to `- --configuration-name=capsule-default` while the Helm Chart uses the default value `--configuration-name=default`.

According to the _real default value_ 

`flag.StringVar(&configurationName, "configuration-name", "default", "The CapsuleConfiguration resource name to use")`

we should make them consistent.

**Comment by prometherion** [comment]
We cannot because `kustomize` prefixes all the created resources with the name of the operator, `capsule` in our case.

I have to investigate if we can change this behavior using the `kustomization` file.

**Comment by bsctl** [comment]
> We cannot because `kustomize` prefixes all the created resources with the name of the operator, `capsule` in our case.
> I have to investigate if we can change this behavior using the `kustomization` file.

Not a big issue, imho: just set the default to:

`flag.StringVar(&configurationName, "configuration-name", "capsule-default", "The CapsuleConfiguration resource name to use")`

**Comment by prometherion** [comment]
I wouldn't change the default name because the default installation method should be Helm and from a developer experience could be silly retrieving the configuration from the CLI.

```bash
kubectl get capsuleconfiguration.clastix.io capsule-default
```

We're already prepending Capsule in the CRD Kind, also in the name would be absolutely non elegant.

**Comment by bsctl** [comment]
revert back?

**Comment by prometherion** [comment]
I don't get the point: reverting what?

**Comment by bsctl** [comment]
> We cannot because kustomize prefixes all the created resources with the name of the operator, capsule in our case.

Going to close as per the comment above.
