### ISSUE TITLE
Getting an error message from Capsule Operator about CA certificate validity

### ISSUE THREAD

**Issue by bsctl** [clastix/capsule#42]
# Bug description
Getting an error message from Capsule Operator about CA certificate validity:

`Error from server (InternalError): Internal error occurred: failed calling webhook "owner.namespace.capsule.clastix.io": Post https://capsule-webhook-service.capsule-system.svc:443/mutate-v1-namespace-owner-reference?timeout=30s: x509: certificate signed by unknown authority`

**Comment by prometherion** [comment]
Yeah, it was expected to be already addressed by #7 by I guess we're facing some further weird issues.

Actually, Capsule is generating its own CA that could take up to some seconds: probably we just need to use the Kubernetes one provided by the Service Account token.

**Comment by prometherion** [comment]
Using CSR from the OperatorSDK code is a bit tricky, need to evaluate if we can fix using our CA and lately with the Kubernetes one.
