### ISSUE TITLE
helm chart 0.1.1 creates invalid yaml with default values

### ISSUE THREAD

**Issue by RixTmobilender** [clastix/capsule#441]
# Bug description
The default value for .Values.webhooks.ingresses.namespaceSelector includes a "matchExpressions" key [that is being merged](https://github.com/clastix/capsule/blob/7db263b2b607d47b06c5609c39b72fcf590b255f/charts/capsule/templates/validatingwebhookconfiguration.yaml#L55-L59)  with the default webhook configuration resulting in invalid YAML 

I believe this regression was introduced in [this commit ](https://github.com/clastix/capsule/commit/6b68363a461d71df768776844c7930063e0d5f8f#diff-5ce40dbdb93f0ca0947537be014959a3658082b1e53eb9977d5e1b0b508b5312R56), by forgetting to delete lines [L57-L59](https://github.com/clastix/capsule/blob/7db263b2b607d47b06c5609c39b72fcf590b255f/charts/capsule/templates/validatingwebhookconfiguration.yaml#L57-L59)
# How to reproduce

Install the helm chart with default values in dry run mode (helm template)

# Expected behavior

Succesful templating of capsule release via helm chart, producing valid YAML.

# Logs

If applicable, please provide logs of `capsule`.

`line 3227: mapping key "matchExpressions" already defined at line 3224`
# Additional context

- Capsule version: 0.1.0
- Helm Chart version: 0.1.1
- Kubernetes version: (`kubectl version`)

**Comment by MaxFedotov** [comment]
Hi @RixTmobilender! Thank you for reporting this, definitely my typo. Will fix in a few hours.

**Comment by prometherion** [comment]
Hey @RixTmobilender, should be fixed by the said MR, Charts is published [here](https://github.com/clastix/charts/blob/gh-pages/capsule-0.1.2.tgz): update your Helm chart and open it back in case of any issue, and thanks for taking a look at Capsule!
