### ISSUE TITLE
Release schedule?

### ISSUE THREAD

**Issue by arminc** [clastix/capsule#472]
# Describe the feature

I was wondering if there is a release schedule and if not what the planning is for the next release as there are some useful features in master.

P.S. This isn't really a feature request, abusing it for this question, as it isn't a bug either.

**Comment by bsctl** [comment]
@arminc Thanks for the interest in Capsule. We're planning it within the end of the month.

**Comment by prometherion** [comment]
Hey @arminc, finally Capsule [v0.1.1](https://github.com/clastix/capsule/releases/tag/v0.1.1) is out there!

It took more time than expected but we're happy for the end result: looking forward to your feedback on it! :eyes:
