### ISSUE TITLE
MutatingWebhookConfiguration

### ISSUE THREAD

**Issue by fagurto** [clastix/capsule#475]
i'm not allow to create MutatingWebhookConfiguration within a tentant , as i understand this happend because this resource is a "cluster wide" resource ,  i've been playing with the RBAC and i've failed miserably ,  is this really posible ???  is there any workaround to be able to do this ??  

the error message that i'm getting is "cannot get resource "mutatingwebhookconfigurations" in API group "admissionregistration.k8s.io" at the cluster scope" .

as a cluster admin a create the folowing resource 

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webhook-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
and also i added the binding through the tenant like so 

apiVersion: capsule.clastix.io/v1beta1
kind: Tenant
metadata:
  name: fagurto-challenge
spec:
  owners:
  - name: fagurto
    kind: User
  additionalRoleBindings:
    - clusterRoleName: 'webhook-role'
      subjects:
        - apiGroup: rbac.authorization.k8s.io
          kind: User
          name: fagurto

the use case for this  was that i was working with in a tenant and i tried to install the so called 'github-action-controller" , so i can have self-hosted github actions runner within the tenant , there were a lot o problems with that installation  but i managed to fix it , the only thing i'm stuck is with  MutatingWebhookConfiguration kind of resource.

best regards.

**Comment by fagurto** [comment]
forgot to mentions , you guys are really awesome 
 i think that capsule is amazing .

**Comment by bsctl** [comment]
Hi @fagurto thanks for your interest in Capsule. We need feedbacks from the users and your is absolutely valuable.

As you guessed, MutatingWebhookConfiguration is a cluster resource and tenants are not allowed to access it. You can create such resources as cluster admin and leave tenants to create runners in their namespaces with additional role bindings, assuming runners are namespaced resources. Hope this helps.

**Comment by prometherion** [comment]
Thanks @fagurto, could you share the use case for needing the ability to put in place Admission Webhoooks?

Let's try to write down a sort of user story so we can evaluate any option!

**Comment by fagurto** [comment]
Hi @prometherion  ,  well ,  basically i was trying to set up a playground for "external users" ,  where i'm working we are currently looking for people to join our devops team , and i designed a challenge where applicants have to set up a ci cd workflow on kubernetes , but one of the requirements was to deploy a self hosted github actions runner (pretty much to see how good they are reading docs , understanding tools and configuring github) . digging around i found this amazing operator called "github action controller"  which is really easy to use and give good functionality , i tried it  myself as a cluster admin  and of course it works like a charm , but when i tried to do it with in the tenant i failed miserably because of what i just told you .  i think this use case is really specific , but also i'm pretty sure there's a ton of tools out there that use this kind of kubernetes resources  that won't work with the current capsule design , and also most of them are package in charts where it's kinda troublesome to split them apart to see which resources are cluster wide and which are namespaced  ( this is basically what a tried to do on the tenants ) .  at then i just stop trying hahaa , the github action controller needs that webhook to work properly so it can't be deploy with in a tenant .

**Comment by fagurto** [comment]
i know i wrote a lot  hahaha sorry about that ,  but my guess is several operators rely on cluster wide resource which makes it imposible to install them with in a tenant . i thinks it's pretty awesome to have control a restrict  some aspect and give the hability to deploy freely .  deploying stuffs is fun but have the oportunity to try new stuffs is also part of what we do .
thumbs up for you guys , i still think capsule is amazing .

**Comment by bsctl** [comment]
@fagurto thanks for the explanation. It looks to me you are looking for an hard multi tenancy where each tenant has access to his/her control plane, so he/she can install CRDs, Policies, AdmissionWebhooks, etc. Capsule has been designed as a soft multi tenancy solution with a single control plane shared between all tenants. As multi tenancy focused guys we’re working on a hard multi tenancy solution too. It’s called Project Kamaji and it’s still under high development. Stay tuned. Thanks

**Comment by prometherion** [comment]
Closing this issue and linking the [Kamaji](https://github.com/clastix/kamaji) repository.
