### ISSUE TITLE
Helm chart - imagePullSecrets are not applied to post-install-job and pre-delete-job

### ISSUE THREAD

**Issue by slushysnowman** [clastix/capsule#486]
# Bug description

To prevent external dependencies, we are replicating Capsule images to a private repo, for which we need to auth. However, we run into issues with the post-install-job and pre-delete jobs, as these don't have imagePullSecrets specified in the spec.

- https://github.com/clastix/capsule/blob/master/charts/capsule/templates/post-install-job.yaml
- https://github.com/clastix/capsule/blob/master/charts/capsule/templates/pre-delete-job.yaml

# How to reproduce

1. Store kubectl and capsule images in a private repo
2. Specify imagePullSecrets in helm chart values and modify image source repository to private repo
3. Install helm chart using values

# Expected behavior

imagePullSecrets specified via helm chart values should also be applied to post-install-job and pre-delete-job if specified.

# Logs

If applicable, please provide logs of `capsule`.

In a standard stand-alone installation of Capsule,
you'd get this by running `kubectl -n capsule-system logs deploy/capsule-controller-manager`.

# Additional context

- Capsule version: 0.1.0
- Helm Chart version: v0.1.3

**Comment by prometherion** [comment]
Hey @slushysnowman, you're totally right: would you like to contribute to this?

Just let me know so I can track it properly!

**Comment by slushysnowman** [comment]
Yep, I'll work on this, was literally about to start.

**Comment by prometherion** [comment]
[Chart has been released](https://github.com/clastix/charts/blob/gh-pages/capsule-0.1.4.tgz), update your local repository! 👀
