### ISSUE TITLE
Document how to secure the Capsule environment with PSP

### ISSUE THREAD

**Issue by prometherion** [clastix/capsule#5]
Making a CaaS platform means Tenant owner Pods could run on the same node: an attacker could start a privileged one, getting root access on the machine, and obtain privilege escalation.

A document explaining how to set up a simple [Pod Security Policy ](https://kubernetes.io/docs/concepts/policy/pod-security-policy) would be great, explaining why a Cluster Admin should deny getting Pods running as privileged, denying to perform host mounting, or host using the host network, etc.

I'm pretty confident that Capsule is not responsible to set this up and must be performed by the Cluster Admin, rather.

**Comment by bsctl** [comment]
@prometherion just started to address this issue. Following kubernetes [guidelines](https://kubernetes.io/docs/concepts/security/pod-security-standards/) we should assign the SA in the `capsule-system` namespace the RBAC to use a permissive PSP. This could be a _pre-requisite_ for example before to install Capsule in a PSP-enabled cluster.

**Comment by bsctl** [comment]
PodSecurityPolicies for Capsule Operator can be enabled when installing Capsule with its helm chart https://github.com/clastix/capsule-helm-chart. It is documented into the chart.
