### ISSUE TITLE
OwnerSpec List in CRD

### ISSUE THREAD

**Issue by gkarthiks** [clastix/capsule#522]
# Bug description

As of today the CRD  [here](https://github.com/clastix/capsule/blob/master/charts/capsule/crds/tenant-crd.yaml#L487) shows the `owner`  with `properties` and defines the `type` as `obejct`. Shouldn't this be as an array like below?

```diff
owner:
+   items:
     description: OwnerSpec defines tenant owner name and kind
     properties:
       kind:
         enum:
           - User
           - Group
         type: string
       name:
         type: string
     required:
       - kind
       - name
     type: object
+  type: array
```

I am using [cdk8s](https://cdk8s.io/) to create the manifests through the code and deploy it via pipeline. There's a functionality in the cdk8s for adding the CRDs. This functionality in cdk8s is called as [import](https://cdk8s.io/docs/latest/cli/import/#crds).

To import the Capsule CRDs, I took the latest CRDs from [here](https://github.com/clastix/capsule/tree/master/charts/capsule/crds) and ran the import function. But the owner in the TenantSpec is not imported as an array, rather it looks like the blow

### TenantSpec  rendered by cdk8s

```golang
type TenantSpec struct {
	Owner *TenantSpecOwner `json:"owner" yaml:"owner"`
	AdditionalRoleBindings *[]*TenantSpecAdditionalRoleBindings `json:"additionalRoleBindings" yaml:"additionalRoleBindings"`
	ContainerRegistries *TenantSpecContainerRegistries `json:"containerRegistries" yaml:"containerRegistries"`
	ExternalServiceIPs *TenantSpecExternalServiceIPs `json:"externalServiceIPs" yaml:"externalServiceIPs"`
	IngressClasses *TenantSpecIngressClasses `json:"ingressClasses" yaml:"ingressClasses"`
	IngressHostnames *TenantSpecIngressHostnames `json:"ingressHostnames" yaml:"ingressHostnames"`
	LimitRanges *[]*TenantSpecLimitRanges `json:"limitRanges" yaml:"limitRanges"`
	NamespaceQuota *float64 `json:"namespaceQuota" yaml:"namespaceQuota"`
	NamespacesMetadata *TenantSpecNamespacesMetadata `json:"namespacesMetadata" yaml:"namespacesMetadata"`
	NetworkPolicies *[]*TenantSpecNetworkPolicies `json:"networkPolicies" yaml:"networkPolicies"`
	NodeSelector *map[string]*string `json:"nodeSelector" yaml:"nodeSelector"`
	ResourceQuotas *[]*TenantSpecResourceQuotas `json:"resourceQuotas" yaml:"resourceQuotas"`
	ServicesMetadata *TenantSpecServicesMetadata `json:"servicesMetadata" yaml:"servicesMetadata"`
	StorageClasses *TenantSpecStorageClasses `json:"storageClasses" yaml:"storageClasses"`
}

```

### TenantSpecOwner rendered by cdk8s

```golang
// OwnerSpec defines tenant owner name and kind.
type TenantSpecOwner struct {
	Kind TenantSpecOwnerKind `json:"kind" yaml:"kind"`
	Name *string             `json:"name" yaml:"name"`
}

type TenantSpecOwnerKind string

const (
	TenantSpecOwnerKind_USER  TenantSpecOwnerKind = "USER"
	TenantSpecOwnerKind_GROUP TenantSpecOwnerKind = "GROUP"
)
```

I know the change of the owner involves the change in the printer columns and a few other places. Looking for a suggestion here.

**Comment by bsctl** [comment]
@gkarthiks Thanks for using Capsule. It seems you're actually referring to the `v1alpha1` CRD version. The current `v1beta1` the `owners` field is an array [here](https://github.com/clastix/capsule/blob/7fefe4f6dedcdf5c600f4edc0f55657ab4bfbb5b/charts/capsule/crds/tenant-crd.yaml#L1112).

**Comment by gkarthiks** [comment]
> @gkarthiks Thanks for using Capsule. It seems you're actually referring to the `v1alpha1` CRD version. The current `v1beta1` the `owners` field is an array [here](https://github.com/clastix/capsule/blob/7fefe4f6dedcdf5c600f4edc0f55657ab4bfbb5b/charts/capsule/crds/tenant-crd.yaml#L1112).


yup, my bad. The sdk am using is not considering the array of versions on the CRD. Thank you. I'll close this issue.

**Comment by gkarthiks** [comment]
Also liked the neat en**capsul**ation of the `NamespaceOptions`, `ServiceOptions`. :rocket: 🏅
