### ISSUE TITLE
Upgrade Helm chart with new CapsuleConfiguration annotations

### ISSUE THREAD

**Issue by maxgio92** [clastix/capsule#526]
# Describe the feature

This issue tracks the needing to upgrade the Helm chart, after #523 will be approved, merged and released.

# What would the new user story look like?

`TBD`

# Expected behavior

The Helm chart should be able to populate the annotation values in the `CapsuleConfiguration`, of which the support will be introduced by #523.

**Comment by prometherion** [comment]
Chart has been upgraded in #523, closing.
