### ISSUE TITLE
Documenting how to integrate the Kubernetes Dashboard with Capsule Proxy

### ISSUE THREAD

**Issue by prometherion** [clastix/capsule#551]
Since it works, why not share it with the community?

**Comment by oliverbaehler** [comment]
@prometherion Maybe it could make sense offering a kubernetes dashboard chart with capsule-proxy, which directly integrates with the proxy :). Or do you think that's a bad idea?

**Comment by prometherion** [comment]
Would you go with a fork of the Kubernetes dashboard chart? May I ask you to elaborate a bit more?

**Comment by bsctl** [comment]
@prometherion this seems fixed by #724
