### ISSUE TITLE
Review RetryOnConflict usages

### ISSUE THREAD

**Issue by pierDipi** [clastix/capsule#57]
# Bug description

In multiple places, there are `retry.RetryOnConflict` usages that are unnecessary or misused.

https://github.com/clastix/capsule/blob/ee469ce2e78f478c123478203746745478e4ae4b/controllers/tenant_controller.go#L566-L569

https://github.com/clastix/capsule/blob/a29db95ad3d04fce6664fd7c6693f935ac44b328/controllers/namespace_controller.go#L172-L181

For both the above `Update` calls, a conflicting update should never happen given the leader's election.

https://github.com/clastix/capsule/blob/a29db95ad3d04fce6664fd7c6693f935ac44b328/controllers/namespace_controller.go#L163-L166

The above needs to retrieve the namespace and update it inside the callback.

**Comment by prometherion** [comment]
thanks for the issue @pierDipi :rocket: 

Working on this with proper PR.

**Comment by prometherion** [comment]
Outdated, closing.
