### ISSUE TITLE
How to pronunce it

### ISSUE THREAD

**Issue by bsctl** [clastix/capsule#59]
How to pronunce "_capsule_"?
It should be pronounced as /ˈkæpsjuːl/ with a bit of french accent :)

**Comment by prometherion** [comment]
![image](https://user-images.githubusercontent.com/9697646/90308118-01f20b80-dedd-11ea-8b5f-416e9cca7992.png)

What I really love from this pronounce is the presence of the *k*... That's a Kubernetes reference!
