### ISSUE TITLE
Capsule proxy endpoint failing to list Priorityclass for tenant even with ProxySettings specifying List verb for PriorityClasses

### ISSUE THREAD

**Issue by mathuvenkat** [clastix/capsule#646]
# Bug description

Filtering does not work for StorageClasses,PriorityClasses on querying the capsule proxy endpoint after setting up the resources with label name and explicitly allowing list verb in the tenant yaml.
CC: @bsctl 

# How to reproduce

1. Provide the Capsule Tenant YAML definitions
```
apiVersion: capsule.clastix.io/v1beta1
kind: Tenant
metadata:
  creationTimestamp: "2022-09-26T20:12:53Z"
  generation: 6
  name: tenantext
  resourceVersion: "1695546"
  uid: 98770539-8573-4dfb-b61c-5dfd16d22c1a
spec:
  owners:
  - kind: ServiceAccount
    name: system:serviceaccount:default:privtest
    proxySettings:
    - kind: Nodes
      operations:
      - List
    - kind: StorageClasses
      operations:
      - List
    - kind: IngressClasses
      operations:
      - List
    - kind: PriorityClasses
      operations:
      - List
  priorityClasses:      #tried without this allowed block as well 
    allowed:
    - high-priority-mv
    allowedRegex: \w+priority
status:
  namespaces:
  - privtest-ns
  - privtest-ns-alt
  size: 2
  state: Active
```
3. Provide all managed Kubernetes resources

```
% k get PriorityClass
NAME                      VALUE        GLOBAL-DEFAULT   AGE
high-priority-mv          1000         false            3h41m
system-cluster-critical   2000000000   false            202d
system-node-critical      2000001000   false            202d
```

Priorityclass
```
apiVersion: scheduling.k8s.io/v1
description: high priority
kind: PriorityClass
metadata:
  creationTimestamp: "2022-09-27T16:13:24Z"
  generation: 1
  labels:
    name: high-priority-mv
  name: high-priority-mv
  resourceVersion: "1686153"
  uid: 6607252f-4e29-40e8-addc-1878475ff17f
preemptionPolicy: PreemptLowerPriority
value: 1000
```
SA: used is privtest 
```
 k get sa
NAME       SECRETS   AGE
default    1         202d
privtest   1         24h
```

capsule proxy e/p
```
k get svc -n capsule-system
NAME                                         TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                        AGE
capsule-controller-manager-metrics-service   ClusterIP   10.101.131.59    <none>        8080/TCP                                       25h
capsule-proxy                                ClusterIP   10.99.132.100    <none>        9001/TCP                                       25h
capsule-proxy-metrics-service                ClusterIP   10.111.202.255   <none>        8080/TCP                                       25h
capsule-proxy-nodeport                       NodePort    10.99.55.228     <none>        9001:30855/TCP,8080:31621/TCP,8081:31892/TCP   22h
capsule-webhook-service                      ClusterIP   10.96.16.175     <none>        443/TCP                                        25h
```

# Expected behavior
Made a curl call to the capsule-proxy endpoint 10.99.132.100:9001 using the token of this SA system:serviceaccount:default:privtest - defined as the owner in tenant.yaml

Call to list PriorityClasses fails
```
curl -k https://10.99.132.100:9001/api/v1/PriorityClasses  --header "Authorization: Bearer <>"
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "**PriorityClasses is forbidden: User \"system:serviceaccount:default:privtest\" cannot list resource \"PriorityClasses\" in API group \"\" at the cluster scope**",
  "reason": "Forbidden",
  "details": {
    "kind": "PriorityClasses"
  },
  "code": 403
}
```
List nodes /namespaces returns results as expected - 200 response 
```
curl -k https://10.99.132.100:9001/api/v1/nodes --header "Authorization: Bearer <same token>"
curl -k https://10.99.132.100:9001/api/v1/namespaces --header "Authorization: Bearer <same token>"
```

Another issue observed here - /nodes fails with forbidden  **note the case "N"**
```
curl -k https://10.99.132.100:9001/api/v1/Nodes
"message": "Nodes is forbidden: User \"system:serviceaccount:default:privtest\" cannot list resource \"Nodes\" in API group \"\" at the cluster scope"
```

# Logs

If applicable, please provide logs of `capsule`.

In a standard stand-alone installation of Capsule,
you'd get this by running `kubectl -n capsule-system logs deploy/capsule-controller-manager`.

# Additional context

- Capsule version: (`capsule --version`)
- Helm Chart version: (`helm list -n capsule-system`)
```
% helm list -n capsule-system
NAME         	NAMESPACE     	REVISION	UPDATED                             	STATUS  	CHART              	APP VERSION
capsule      	capsule-system	1       	2022-09-26 11:34:20.249276 -0700 PDT	deployed	capsule-0.1.11     	0.1.2
capsule-proxy	capsule-system	1       	2022-09-26 11:48:58.208154 -0700 PDT	deployed	capsule-proxy-0.3.1	0.3.0
```
- Kubernetes version: (`kubectl version`)
% k version
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/arm64"}
```

**Comment by prometherion** [comment]
Thanks for reporting this, @mathuvenkat.

Let me check this so I can evaluate if the fix must be addressed in the Capsule code base or, rather, in the capsule-proxy one.

**Comment by prometherion** [comment]
I was able to replicate the issue you reported, and the main problem is that `PriorityClass` objects [are not labelled as requested](https://capsule.clastix.io/docs/general/proxy#priority-classes):

> The name label reflecting the resource name is mandatory, otherwise filtering of resources cannot be put in place
> ```json
> apiVersion: scheduling.k8s.io/v1
> kind: PriorityClass
> metadata:
>   labels:
>     name: custom
>   name: custom
> value: 1000
> globalDefault: false
> description: "Priority class for Tenants"
> ```

Please, note the label `name` matches the `metadata.name` value.

Since `capsule-proxy` is totally relying on the filtering capabilities offered by Kubernetes API Server, this labelling is required to avoid rewriting yet another Kubernetes API Server.

If you're able to get it solved, please, close the issue.

**Comment by mathuvenkat** [comment]
Thanks @prometherion for replicating this issue.
I had provided in my original comment the yaml of Priority class where metadata.name and labels.name is same, which is high-priority-mv. This should be sufficient right, but it did not work ? Is there anything I missed here ?


```
apiVersion: scheduling.k8s.io/v1
description: high priority
kind: PriorityClass
metadata:
  creationTimestamp: "2022-09-27T16:13:24Z"
  generation: 1
  labels:
    name: high-priority-mv
  name: high-priority-mv
  resourceVersion: "1686153"
  uid: 6607252f-4e29-40e8-addc-1878475ff17f
preemptionPolicy: PreemptLowerPriority
value: 1000
```

**Comment by prometherion** [comment]
> I had provided in my original comment the yaml of Priority class where metadata.name and labels.name is same, which is high-priority-mv. This should be sufficient right, but it did not work ? Is there anything I missed here ?

Correct, just the label `name` is required.

> It did not work with the same yaml you provided above, when I made a curl call to the proxy endpoint as below curl -k https://10.102.192.222:9001/api/v1/priorityclasses
> 
> "priorityclasses is forbidden: User "system:serviceaccount:infra-admin-tenant-ns-abc:tenant-owner-admin" cannot list resource "priorityclasses" in API group "" at the cluster

I'm not getting the point here: in the tenant manifest the user `system:serviceaccount:default:privtest` is reported as the tenant owner, however, the last message is referring to the ServiceAccout `tenant-owner-admin` in the namespace `infra-admin-tenant-ns-abc`.

> Also what is the clusterrolebinding that capsule creates that will allow this

Due to limitations of Kubernetes API which RBAC has been designed around resources rather than user ownerships, there's no role allowed to list those cluster-scoped resources: the proxy has to run as cluster administrator in order to perform the required user impersonation, and access all the required objects such as Storage Class, Ingress Class, Priority Class, etc.

**Comment by prometherion** [comment]
Closing due to stale activity, feel free to open it back if you're still having the described issue.
