### ISSUE TITLE
Support for custom user group

### ISSUE THREAD

**Issue by MaxFedotov** [clastix/capsule#66]
# Describe the feature

Hi guys, thank's a lot for a great tool for managing multi-tenant k8s :) 

We are now trying to adopt it in our environment and found that right now it's impossible to use custom UserInfo.Group in webhooks so they apply only for specific users, as it's hardcoded as `capsulev1alpha1.GroupVersion.Group`. As we already have a dedicated AD group for k8s users, it will be good if we can use it with Capsule too, without a need to provision one more group and move users into it.

I will submit a PR with this small patch.

Thanks,
Max

**Comment by prometherion** [comment]
Thanks Max, honestly we were thinking about a feature proposal like this, so happy to get this! 🚀 

As your PR pointed out, managing this through a CLI argument is the most elegant implementation, I'll check out the PR ASAP!
