### ISSUE TITLE
Allow tenant name as namespace name when using forceTenantPrefix=true

### ISSUE THREAD

**Issue by omallo** [clastix/capsule#683]
# Describe the feature

When using the `forceTenantPrefix=true` configuration option, I would like Capsule to allow using the tenant name w/o any extension as namespace name for that tenant. Currently, Capsule expects the namespace name to have at least one more character than the tenant name.

# What would the new user story look like?

1. The cluster admin creates a tenant named `oil-prod`.
2. The admin of the `oil-prod` tenant creates a namespace named `oil-prod`.
3. Capsule accepts the namespace name and associates it to the tenant.

# Expected behavior

Step 2 above should not lead to an error where Capsule rejects the namespace name. This is especially relevant for project tenants where 1 namespace is enough in which case I would like to use the tenant name as namespace name w/o having to "invent" a suffix.

**Comment by prometherion** [comment]
Hey, thanks for giving it a try Capsule, really appreciated!

The feature has been implemented and requested by @MaxFedotov (IIRC), so tagging him to get his feedback on that too.

The prefix feature has been designed mostly to avoid Namespace name collisions that could start also a privilege escalation. 

Your use case is a bit weird, tho: why use a single Namespace for a Tenant, which by its definition is a collection of Namespace resources?

If you could, having more context would help us in defining a user story, and understand if Capsule can play a role there.

**Comment by omallo** [comment]
@prometherion , thanks for the quick feedback!

In my case, I have several projects and every project is deployed to different stages (`dev`/`test`/`prod`). I'm modeling every combination of a project and stage as a separate tenant, so e.g. I would have the tenants `myproject-dev`, `myproject-test`, and `myproject-prod`.

For the `dev` and `test` stages, I typically have multiple namespaces simulating substages like e.g. `myproject-dev-one`. However, on `prod`, I never deploy different versions of my applications and this is why I always have a single namespace which I would like to name `myproject-prod` as the tenant itself.

I guess that the following characteristics of my setup lead to the feature request I placed:
- My tenants are rather fine grained, as I have many, small to medium-sized projects.
- I typically deploy applications belonging to a project to a single namespace since they often are a bunch of functional microservices for which I don't have the need to split them up into separate namespaces within a single stage.

**Comment by MaxFedotov** [comment]
Hi @omallo,

What about naming your tenants like this:
`myproject-dev`
`myproject-test`
`myproject`
and then in the tenant `myproject` create namespace `myproject-prod`?

**Comment by omallo** [comment]
@MaxFedotov , this is an option I had considered, however, I didn't like that w/ this naming scheme, the tenant `myproject` is a prefix of other tenants.

Another alternative I'm considering is having a standard suffix I add to every namespace of a tenant (e.g. `-apps`).

Both alternatives are not ideal in my case but if you consider my use case to be a bit exotic, I could live with one of the alternatives.

**Comment by prometherion** [comment]
Marking this as a stale issue, feel free to open it back.

Ideally, the topic should be raised during a community call, and finding a consensus with the core maintainers.
