### ISSUE TITLE
feat: Allow GlobalTenantResource to cluster-scoped

### ISSUE THREAD

**Issue by h4wkmoon** [clastix/capsule#697]
# Describe the feature

So far, globalTenantResources are namespaced. This feature would allow a globalTenantResource to be cluster-scoped.

# What would the new user story look like?

As a cluster-admin, I can create one cluster-scoped resource for each namespace created in a tenant.

# Use-case
* For each teant namespace, we currently create a calico globalnetworkpolicy. This is something like a netpol, but cluster-scoped.

**Comment by prometherion** [comment]
It seems to me out of scope, honestly.
According to your preferred CD strategy, you can provision a Tenant and along with it additional resources, such as your ClusterScopes resources.

The Capsule domain is related to Multi-Tenant and to the limitations of Kubernetes Namespaces, such as replicating resources across a set of these and orchestrating them.

ClusterScope resources should be provisioned by cluster administrators, and they have already full access to the cluster, thus are no limitations at all.

May I ask you for a further user story with a real use case to understand better your need?

**Comment by h4wkmoon** [comment]
Sure.
When a tenant owner creates a namespace in one of his/her tenants, our current multi-tenancy operator creates some gnp to allow/deny some traffic to/from this namespace.

**Comment by prometherion** [comment]
We're lost in translation, I guess, so I'll try to explain what's wrong according to the Capsule jargon.

- Tenants aren't created by Tenant Owners, but rather by the Cluster Administrator
- Tenant Owners can just create Namespace resources

I recall @MaxFedotov is using Calico `GlobalNetworkPolicy` for their tenants, would be great to have his feedback on the discussion.

> our current multi-tenancy operator creates some gnp to allow/deny some traffic to/from this namespace

@bsctl @ptx96 can add their usage so far about Capsule in onboarding and offboarding Tenants in a GitOps way.

**Comment by bsctl** [comment]
@h4wkmoon In the Capsule design, the Tenant owner's realm is the group of namespaces being part of the tenant kept togheter by Capsule. The tenant creation as well as other global resources as for example nodes, Storage Classes, GlobalNetworkPolicies, are responsibility of the Cluster Admin. A Tenant owner cannot create global cluster-scoped resources.

As part of tenant onboarding procedure, the cluster admin (or any user with admin capabilities) creates the Tenant Resources as well as the other global resources related to the tenant: Storage, Ingress Classes, ClusterRoles, GlobalNetworkPolicies etc.

**Comment by h4wkmoon** [comment]
@bsctl , I understand that. And for most of the resources I agree, of course. Most of them can be seen as "infrastructure" or "plateform" stuff, and clearly, have nothing to do with capsule.
But what about globalnetworkpolicies that are created specifically for a namespace ?

**Comment by MaxFedotov** [comment]
> I recall @MaxFedotov is using Calico GlobalNetworkPolicy for their tenants, would be great to have his feedback on the discussion.

Our level of granularity is the whole tenant. We don't create `GlobalNetworkPolicy` for each ns, because it seems a bit impractical - the whole tenant is owned by a separate team, so there is no need to segregate their workloads from each other

**Comment by prometherion** [comment]
> But what about globalnetworkpolicies that are created specifically for a namespace ?

It's s problem, you're right, and I'm not sure it's responsibility of Capsule to solve it.

I got strong opinions, weakly held, let's try to talk about this on one of the upcoming community meetings finding a consensus and writing down the result of it.

**Comment by bsctl** [comment]
> It's s problem, you're right, and I'm not sure it's responsibility of Capsule to solve it.

cannot agree more

**Comment by bsctl** [comment]
@h4wkmoon could you please an example of globalNetworkPolicy you’re going to create for each namespace? Probably you can solve the problem in a different way. Being “global” you do not need to create it for each namespace. A namespaced networkPolicy seems to me more suitable. And Capsule already helps on that.

**Comment by h4wkmoon** [comment]
No need. It looks like my current use-case is not a good one. I'm going to stop wasting everyone's time. 
Sorry, and thank you for the fish. :laughing:

**Comment by prometherion** [comment]
> I'm going to stop wasting everyone's time

You are not wasting time, we're open to continuing the discussion at one of the next community meetings. Feel free to raise the topic for the next agenda items on the [#capsule](https://kubernetes.slack.com/archives/C03GETTJQRL) channel.
