### ISSUE TITLE
tenent user with view permission on pods is able to create ns

### ISSUE THREAD

**Issue by jiten-kmar** [clastix/capsule#709]
# Bug description

we created a tenant owner and one user which only has permissions to get and watch pods. Tenant owner works fine but inspite tenant user is able to create a new namespace. 

# How to reproduce

here is my pod viewer file

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]

# Expected behavior

# Logs

If applicable, please provide logs of `capsule`.

In a standard stand-alone installation of Capsule,
you'd get this by running `kubectl -n capsule-system logs deploy/capsule-controller-manager`.

# Additional context

- Capsule version: (`capsule --version`)
- Helm Chart version: (`helm list -n capsule-system`)
- Kubernetes version: (`kubectl version`)

**Comment by MaxFedotov** [comment]
hi @jitender1278!

Can you please provide your `Tenant` and `CapsuleConfiguration` specs, as well as information about group membership for owner and user

**Comment by meetdpv** [comment]
Here are the files and tenant-viewer has custom cluster role of eks-readonly-user-role for pod get,list, watch but it is still able to create namespace. However this user is not able list namespaces at cluster level nor able delete the namespace it created.

Tenant file ------------------------------
apiVersion: capsule.clastix.io/v1beta2
kind: Tenant
metadata:
  name: app4
spec:
  owners:
  - name: tenant-owner
    kind: User
  - name: tenant-viewer
    kind: User
    clusterRoles:
      - eks-readonly-user-role

Cluster Role --------------------------------------
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: eks-readonly-user-role
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["deployments", "replicasets", "pods"]
  verbs: ["get", "list", "watch"]

 
Capsule Configuration -------------------------------
apiVersion: capsule.clastix.io/v1beta2
kind: CapsuleConfiguration
metadata:
  annotations:
    meta.helm.sh/release-name: capsule
    meta.helm.sh/release-namespace: capsule-system
  creationTimestamp: "2023-02-06T23:32:38Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: capsule
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: capsule
    app.kubernetes.io/version: 0.2.1
    helm.sh/chart: capsule-0.3.1
  name: default
  resourceVersion: "74737"
  uid: 03d8a754-a7e5-4f96-bfce-48bbb44db873
spec:
  enableTLSReconciler: true
  forceTenantPrefix: false
  overrides:
    TLSSecretName: capsule-tls
    mutatingWebhookConfigurationName: capsule-mutating-webhook-configuration
    validatingWebhookConfigurationName: capsule-validating-webhook-configuration
  protectedNamespaceRegex: ""
  userGroups:
  - capsule.clastix.io

**Comment by prometherion** [comment]
Once you define a user as a Tenant Owner, this is entitled to create Namespace resources for that tenant.

Your manifest definition is wrong, you have to add the read only user to `/spec/additionalRoleBindings/`.

Please, take a look to the officiale [documentation](https://capsule.clastix.io/docs/general/tutorial/#roles-assigned-to-tenant-owners):

> Please, note that, despite created with more restricted permissions, a tenant owner can still create namespaces in the tenant because he belongs to the capsule.clastix.io group. If you want a user not acting as tenant owner, but still operating in the tenant, you can assign additional RoleBindings without assigning him the tenant ownership.

**Comment by prometherion** [comment]
Closing due to lack of feedback.
