### ISSUE TITLE
how capsule integrate with rancher under openLDAP

### ISSUE THREAD

**Issue by zhoushuke** [clastix/capsule#761]
# Describe the feature

after read capsule doc, I have some confusion about teant owner with --capsule-user-group 

# What would the new user story look like?

in my environment, using rancher to manager kubernetes cluster, rancher integrates with my company LDAP auth system, so everyone can use self ldap account to login rancher and operators the cluster object, of course  they have right permissions.

if I want capsule to support multi-tenant functionto to isolate resource usage, But I don't know how to sign a ldap account as tenant owner, no doc describes clearly.

I notice there is a hack/create-user.sh for a example, I had a try, but I perfer to reuse rancher user system(directly use ldap system is ok) instead of resigning x509 for everyone.

thanks so much.

# Expected behavior
A clear operators with ldap auth system, since ldap used so popular.

**Comment by prometherion** [comment]
Thanks for asking, @zhoushuke!

It seems to me a question more related to the Rancher and Capsule integration, and I'm begging for double-confirm from @maxgio92 that worked on the development of the [Rancher extension](https://github.com/clastix/rancher-extension-clastix).

The Rancher architecture is expecting a `local` cluster acting as a management cluster which provides the basic functionalities, such as authentication through the IdP connection.

This authentication is required to provide centralized management of users to the workload clusters, where Capsule could be installed: essentially when a user wants to deploy an application, is connecting to the desired cluster through a `kubeconfig` that is responsible of forward the request on the behalf of the user.

The users' requests are forwarded to the workload cluster using [user impersonation](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#user-impersonation): the addon deployed on the workload cluster is forwarding the request according to the user authentication details, such as the name, and the group provided by Rancher IdP integration.

For Capsule, we need to find the user group entitled to the multi-tenant capabilities, and with our tests, it was something as `keycloakoidc_group://capsule.clastix.io`: please, notice the `keycloakoidc_group` prefix and the divisor `://`, so `capsule.clastix.io` is referring to the effective group defined on the Keycloak group.

Pretty similar to users: we had to use the Rancher ID membership of imported users you can find in the Rancher dashboard path `/dashboard/c/local/auth/management.cattle.io.user`, e.g. `u-ygrzuujwte`.

I'd say the first thing you have to do is to configure Rancher with the OpenLDAP integration, and starting from there, ensure and double-check how the groups' membership is replicated in Rancher.

**Comment by zhoushuke** [comment]
@prometherion @maxgio92  nice work, yes like keycloakoidc, with [user impersonation](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#user-impersonation) in kubernetes, 
if a group in openldap like: CN=group_name,OU=xxx,DC=yyy,DC=zzz,
mapping to kubernetes group would be like openldap_group://CN=group_name, OU=xxx,DC=yyy,DC=zzz

**Comment by maxgio92** [comment]
Oh, @zhoushuke so in the Kubernetes `Group` in the requests made through Rancher authenticating with OpenLDAP, you have all the queries? CN is included, isn't it?

**Comment by prometherion** [comment]
According to the various examples I found so far, it seems so.

https://pkg.go.dev/github.com/canhnt/rancher-go/cmd/rancherctl

```yaml
projects:
  - id: 'c-a1b2c3:p-b1c2d3'
    name: "demo-project1"
    description: "1st project storing in YAML file"
    podSecurityPolicyId: mypsp
    members:
      - type: Group
        principalId: openldap_group://cn=developers,ou=Groups,dc=example
        roleTemplateId: project-member
...
```

With that said, the `openldap_group://...` entry must be declared in the `CapsuleConfiguration` for the `userGroups` key.

If you have multiple groups, all of these must be added.

Please, if this information is enough, feel free to close the issue.
