### ISSUE TITLE
admission webhook denies request to delete Tenant

### ISSUE THREAD

**Issue by atamgp** [clastix/capsule#764]
# Bug description

Cannot delete Tenant anymore

# How to reproduce
In Ginkgo test, we get an error when deleting a Tenant object:
Error from server: admission webhook "tenants.capsule.clastix.io" denied the request: Tenant.capsule.clastix.io "forza" not found

**Test code**
```
err := k8s.KubectlApplyFromStringE(f.GetT(), k8sOptions, tenant)
		gomega.Expect(err).Should(gomega.BeNil())
		// Create tenant
		tenantCreated, createErr := k8s.RunKubectlAndGetOutputE(f.GetT(), k8sOptions, "get", "tenant", "forza", "-otemplate='{{.status.state}}'")
		gomega.Expect(createErr).Should(gomega.BeNil())

		//Check if tenant is Active
		assert.Contains(f.GetT(), tenantCreated, "Active")
		time.Sleep(10 * time.Second)

		// Cleanup tenant
		tenantDelete, deleteErr := k8s.RunKubectlAndGetOutputE(f.GetT(), k8sOptions, "delete", "tenant", "forza")
		assert.Contains(f.GetT(), tenantDelete, "deleted")
		gomega.Expect(deleteErr).Should(gomega.BeNil())
```

This worked with older versions on Capsule. 
According to the admission webhook the tenant object does not exist, but form my kubectl promt I can just see and delete it....

Falling back from chart 0.4.2 to 0.4.0 it works...
Probably related to this PR:
https://github.com/clastix/capsule/pull/736/files
	

# Expected behavior
no error, delete Tenant

# Additional context

- Capsule version: 0.3.1 (newest)
- Helm Chart version:  0.4.2

**Comment by prometherion** [comment]
Also, it would be really helpful to have further logs from Capsule to understand if we got a stack trace somewhere.

**Comment by prometherion** [comment]
I tried to replicate your issue, although in a different way:

```
NAME    NAMESPACE       REVISION        UPDATED                                         STATUS          CHART           APP VERSION
capsule capsule-system  1               2023-05-25 14:40:22.855681171 +0200 CEST        deployed        capsule-0.4.2   0.3.1      

$: cat /tmp/tnt.yaml
apiVersion: capsule.clastix.io/v1beta2
kind: Tenant
metadata:
  name: forza
spec:
  owners:
  - kind: User
    name: alice

$: kubectl apply -f /tmp/tnt.yaml
tenant.capsule.clastix.io/forza created

$: kubectl get tnt
NAME    STATE    NAMESPACE QUOTA   NAMESPACE COUNT   NODE SELECTOR   AGE
forza   Active                     0                                 7s
$: kubectl delete tnt forza
tenant.capsule.clastix.io "forza" deleted
```

**Comment by prometherion** [comment]
To double-check I verified the handlers for the `tenants.capsule.clastix.io` route and there are no API client operations, also considering that the `Delete` functions are returning nil, eventually skipping any manipulation.

**Comment by prometherion** [comment]
@atamgp did you have the chance to review my latest messages? I'm here to help you!

**Comment by atamgp** [comment]
@prometherion thanks for the support. The issue has been solved. We had a version mistake on our side.
