### ISSUE TITLE
Critical vulnerabilities in Capsule v0.3.1

### ISSUE THREAD

**Issue by meetdpv** [clastix/capsule#767]
# Bug description

Critical vulnerabilities found in Twistlock scan of Capsule v0.3.1

# How to reproduce
Run on Twistlock scan on Capsule image

Run on Twistlock scan on Capsule image

# Expected behavior

# Logs

If applicable, please provide logs of `capsule`.

In a standard stand-alone installation of Capsule,
you'd get this by running `kubectl -n capsule-system logs deploy/capsule-controller-manager`.

# Additional context

- Capsule version: (`capsule --version`) v0.3.1
- Helm Chart version: (`helm list -n capsule-system`) v0.3.1
- Kubernetes version: (`kubectl version`)

**Comment by prometherion** [comment]
May I ask you to add the twistlock output to the issue, please?

**Comment by prometherion** [comment]
@slimm609 do you think this could be related to your Go version bump-up with #759?

**Comment by slimm609** [comment]
Cutting a new release with the changes already in `master` branch will resolve these CVEs

**Comment by prometherion** [comment]
I'd close this once since addressed with #759.
