### ISSUE TITLE
Resource quota annotations for storage class limits may be too long

### ISSUE THREAD

**Issue by radekg** [clastix/capsule#772]
# Bug description

When using resource quotas tenant functionality to manage storage class request limits, annotation generated by Capsule very often exceeds the 63 characters length in the name part of the annotation.

# How to reproduce

Create a tenant with request quotas like:

```yaml
resourceQuotas:
  items:
    - hard:
        some-storage-class-name.storageclass.storage.k8s.io/requests.storage: 10Gi
```

Capsule will internally attempt to manage its own annotations on a resource quota, two most prominent:

- `quota.capsule.clastix.io/hard-some-storage-class-name.storageclass.storage.k8s.io.requests.storage`
- `quota.capsule.clastix.io/used-some-storage-class-name.storageclass.storage.k8s.io.requests.storage`

Both take a valid annotation of a kubernetes resource quota and convert it into an invalid Capsule annotation on a Capsule-managed resource quota.

# Expected behavior

Feature should not break silently or the limitation must be clearly documented.

# Logs

```
log:{"level":"error","ts":"2023-06-12T08:26:30.352Z","logger":"controllers.Tenant","msg":"Cannot sync ResourceQuota items","Request.Name":"some-request-name","error":"update of outer ResourceQuota items has failed: ResourceQuota "capsule-resource-quota-name" is invalid: [metadata.annotations: Invalid value: "quota.capsule.clastix.io/used-some-storage-class-name.storageclass.storage.k8s.io_requests.storage": name part must be no more than 63 characters, metadata.annotations: Invalid value: "quota.capsule.clastix.io/hard-some-storage-class-name.storageclass.storage.k8s.io_requests.storage": name part must be no more than 63 characters]"}
```

# Additional context

Irrelevant.

**Comment by prometherion** [comment]
Thanks for the report, @radekg.

We have to think if this feature must be promoted to a specification key, or delegated to the ResourceQuota since it can support the ][limit of Custom Resource definition](https://kubernetes.io/docs/concepts/policy/resource-quotas/#object-count-quota).

May I ask your opinion on which solution you prefer between the Capsule and the ResourceQuota one?

**Comment by radekg** [comment]
Happy to hear that the report is well received.  
Hashed values? It seems like it wouldn't be much work but it would have a great benefit.
