### ISSUE TITLE
Critical vulnerabilities in Capsule v0.3.2

### ISSUE THREAD

**Issue by meetdpv** [clastix/capsule#779]
# Bug description

Critical vulnerabilities found during Twistlock scan of Capsule 0.3.2 image

# How to reproduce
Run on Twistlock scan on Capsule image

Twistlock scan report attached for reference
![capsule 0 3 2 scan](https://github.com/clastix/capsule/assets/43143734/36415ee1-d42d-4560-83e2-534314ec924a)

# Expected behavior

No critical vulnerabilities present. We want to take Capsule to higher environments in next couple of weeks so need to get clearance from Security team.

# Logs

If applicable, please provide logs of `capsule`.

In a standard stand-alone installation of Capsule,
you'd get this by running `kubectl -n capsule-system logs deploy/capsule-controller-manager`.

# Additional context

- Capsule version: (`capsule --version`) v0.3.2
- Helm Chart version: (`helm list -n capsule-system`) v0.3.2
- Kubernetes version

: (`kubectl version`)

**Comment by prometherion** [comment]
These are inapplicable CVE reports since Capsule is built with CGO disabled and the reported issues are non affecting Capsule itself.

I'll bump anyway to snooze those alerts since Capsule is used by other organizations that are paying attention to Twistlock reports.
