### ISSUE TITLE
Documented feature doesn't exist anymore

### ISSUE THREAD

**Issue by Limdel** [clastix/capsule#794]
# Bug description

In your documentation I found about namespaces prefixes, which could be enabled by using flag --force-tenant-prefix when running controller manager. However, it doesn't know this flag. I thought the problem is probably in version and I tried different images and the last one where it worked is probably v0.5.0, but there is nothing about deprecation of this feature in the docs.

Is there any other way to enable this feature? If no - will it be implemented again?

# How to reproduce

Specify argument --force-tenant-prefix for the controller.

# Expected behavior

It should run.

# Logs

unknown flag: --force-tenant-prefix

# Additional context

- Capsule version: v0.3.3

**Comment by prometherion** [comment]
You're totally right, that flag has been moved into the `CapsuleConfiguration` resource, rather than as a CLI flag.

It's just a matter of documentation, are you open to taking care of this, @Limdel?

**Comment by devendra-dhakad** [comment]
I will take care @prometherion
