### ISSUE TITLE
Documentation Spelling Mistakes - v2

### ISSUE THREAD

**Issue by whatnick** [clastix/capsule#803]
# Bug description

Like #197 I would like to fix some more spelling in docs that have crept in the last couple of years. Samples from reading [GitOps docs](https://capsule.clastix.io/docs/guides/flux2-capsule#full-setup) are:

`To have a glimp`
instead of
`To have a glimpse`

# How to reproduce

1. Read the docs in full
2. Pay attention to things outside YAML code blocks

# Expected behavior

Slightly better documentation quality

**Comment by whatnick** [comment]
@prometherion I am spending some time today studying the Capsule docs and creating a `capsule.txt` list for a spellchecker automation which we could potentially run in CI here to solve the issue longer term. Would something like this in CI be useful ? https://github.com/marketplace/actions/check-spelling

**Comment by prometherion** [comment]
Closes via #804.
