### ISSUE TITLE
Which apiVersion to use for CRDs and WebhooksConfigurations?

### ISSUE THREAD

**Issue by bsctl** [clastix/capsule#90]
Noted the CRDs and WebhooksConfigurations are installed by `make deploy` script with `apiVersion: v1` and templates files have `apiVersion: v1beta1`. When installing with Helm, we install always with `apiVersion: v1` but this leads to some errors preventing the installation, see: https://github.com/clastix/capsule-helm-chart/issues/5 and https://github.com/clastix/capsule-helm-chart/issues/4.

**Comment by prometherion** [comment]
Which Kubernetes version are you referring to? Tested on Kubernetes 1.18 and works like a charm.

**Comment by bsctl** [comment]
Kubernetes 1.18.5.

https://github.com/clastix/capsule/blob/303fc4d69ca2c8d416422154d5e4b0f27c21ee8a/config/crd/bases/capsule.clastix.io_tenants.yaml#L3

Once installed with `make deploy` , we have:

```
$ kubectl get crd tenants.capsule.clastix.io -o yaml | more
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.3.0
    ...
```

So I assumed v1 in the Helm chart
https://github.com/clastix/capsule-helm-chart/blob/07a759cb1e38aa24ecc8a1a4b0c90a5be8c90230/crds/tenant-crd.yaml#L1

However, we get https://github.com/clastix/capsule-helm-chart/issues/4

Try to deploy with the Helm Chart.

**Comment by MaxFedotov** [comment]
There are some problems with updating to `controller-gen.kubebuilder.io/version: v0.4.0` and `apiVersion: apiextensions.k8s.io/v1`/`admissionregistration.k8s.io/v1`

So the thing is following:
* controller-gen is used to generate crd\deep-copy methods. And it supports `admission.k8s.io/v1`/`admissionregistration.k8s.io/v1`
* But, controller-runtime, which provides an API for writing webhooks, still lack support of admission.k8s.io/v1 (see https://github.com/kubernetes-sigs/controller-runtime/issues/1123, https://github.com/kubernetes-sigs/controller-runtime/issues/1161). So when i updated controller-gen to v0.4.0, generated new crds and uploaded them to kind, I've started getting following errors from all webhooks
```
{"level":"error","ts":1600335087.011634,"logger":"controller-runtime.webhook.webhooks","msg":"unable to decode the request","webhook":"/mutate-v1-service-labels","error":"no kind \"AdmissionReview\" is registered for version \"admission.k8s.io/v1\" in scheme \"pkg/runtime/scheme.go:101\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).ServeHTTP\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/webhook/admission/http.go:79\nsigs.k8s.io/controller-runtime/pkg/webhook.instrumentedHook.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/webhook/server.go:129\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2036\nnet/http.(*ServeMux).ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2416\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2831\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1919"}
{"level":"error","ts":1600335087.2033126,"logger":"controller-runtime.webhook.webhooks","msg":"unable to decode the request","webhook":"/mutate-v1-service-labels","error":"no kind \"AdmissionReview\" is registered for version \"admission.k8s.io/v1\" in scheme \"pkg/runtime/scheme.go:101\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).ServeHTTP\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/webhook/admission/http.go:79\nsigs.k8s.io/controller-runtime/pkg/webhook.instrumentedHook.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/webhook/server.go:129\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2036\nnet/http.(*ServeMux).ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2416\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2831\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1919"}
```
So let's use `controller-gen.kubebuilder.io/version: v0.3.0` and `apiextensions.k8s.io/v1beta1`/` admissionregistration.k8s.io/v1beta1` until controller-runtime will add support for newer versions

**Comment by bsctl** [comment]
@prometherion Close in favour of #98
