### ISSUE TITLE
Use controller library v0.4.0 with v1 CRDs support

### ISSUE THREAD

**Issue by bsctl** [clastix/capsule#98]
# Describe the feature
Use controller library v0.4.0 with v1 CRDs support

# What would the new user story look like?

# Expected behavior

Have Tenant CRD in v1

**Comment by bsctl** [comment]
Assigning to @MaxFedotov as per your request. https://github.com/clastix/capsule-helm-chart/pull/11#discussion_r489655382

**Comment by prometherion** [comment]
What's the reason behind this requirement?

**Comment by MaxFedotov** [comment]
@bsctl please see https://github.com/clastix/capsule/issues/90#issuecomment-694134836
Let's postpone this

**Comment by bsctl** [comment]
@MaxFedotov ok

**Comment by bsctl** [comment]
@MaxFedotov @prometherion hello it looks some work has been done [here](https://github.com/kubernetes-sigs/controller-runtime/issues/1161) and [here](https://github.com/kubernetes-sigs/controller-runtime/pull/1293). Can we consider to move to webhooks to API v1?
